
"""
    This code was generated by Codezu.     

    Changes to this file may cause incorrect behavior and will be lost if
    the code is regenerated.
"""


from mozurestsdk.mozuclient import default as default_client
from mozurestsdk.mozuurl import MozuUrl;
from mozurestsdk.urllocation import UrlLocation
from mozurestsdk.apicontext import ApiContext;

class LocationType(object):
	def __init__(self, apiContext: ApiContext = None, mozuClient = None):
		self.client = mozuClient or default_client();
		client.withApiContext(apiContext);
	
	def getLocationTypes(self,):
		"""
			Retrieve a list of all location types defined for the tenant.
				array|LocationType 
		"""

		url = MozuUrl("/api/commerce/admin/locationtypes/", "GET", UrlLocation.TenantPod, False);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getLocationType(self,locationTypeCode, responseFields = None):
		"""
			Retrieves the details of the location type specified in the request.
			Request Params
				string locationTypeCode The user-defined code that identifies the location type.
				string responseFields Use this field to include those fields which are not included by default.
			Response
				LocationType 
		"""

		url = MozuUrl("/api/commerce/admin/locationtypes/{locationTypeCode}?responseFields={responseFields}", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("locationTypeCode", locationTypeCode);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def addLocationType(self,locationType, responseFields = None):
		"""
			Creates a new location type based on the information specified in the request.
			Request Params
				string responseFields Use this field to include those fields which are not included by default.
				locationType Properties of a type of physical location, such as warehouse or kiosk. Location types enable tenants to group similar locations for filtering and location usage type definition.
			Response
				LocationType 
		"""

		url = MozuUrl("/api/commerce/admin/locationtypes/?responseFields={responseFields}", "POST", UrlLocation.TenantPod, False);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def updateLocationType(self,locationType, locationTypeCode, responseFields = None):
		"""
			Updates the name of a defined location type.
			Request Params
				string locationTypeCode The user-defined code that identifies the location type.
				string responseFields Use this field to include those fields which are not included by default.
				locationType Properties of a type of physical location, such as warehouse or kiosk. Location types enable tenants to group similar locations for filtering and location usage type definition.
			Response
				LocationType 
		"""

		url = MozuUrl("/api/commerce/admin/locationtypes/{locationTypeCode}?responseFields={responseFields}", "PUT", UrlLocation.TenantPod, False);
		url.formatUrl("locationTypeCode", locationTypeCode);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def deleteLocationType(self,locationTypeCode):
		"""
			Deletes the location type specified in the request.
			Request Params
				string locationTypeCode The user-defined code that identifies the location type.
			Response
		"""

		url = MozuUrl("/api/commerce/admin/locationtypes/{locationTypeCode}", "DELETE", UrlLocation.TenantPod, False);
		url.formatUrl("locationTypeCode", locationTypeCode);
		self.client.withResourceUrl(url).execute();

	
	
	