
"""
    This code was generated by Codezu.     

    Changes to this file may cause incorrect behavior and will be lost if
    the code is regenerated.
"""


from mozurestsdk.mozuclient import default as default_client
from mozurestsdk.mozuurl import MozuUrl;
from mozurestsdk.urllocation import UrlLocation
from mozurestsdk.apicontext import ApiContext;

class ExtendedProperty(object):
	def __init__(self, apiContext: ApiContext = None, mozuClient = None):
		self.client = mozuClient or default_client();
		client.withApiContext(apiContext);
	
	def getExtendedProperties(self,orderId, draft = False):
		"""
			orders-extendedproperties Get GetExtendedProperties description DOCUMENT_HERE 
			Request Params
				bool draft If true, retrieve the draft version of the order, which might include uncommitted changes to the order or its components.
				string orderId Unique identifier of the order.
			Response
				array|ExtendedProperty 
		"""

		url = MozuUrl("/api/commerce/orders/{orderId}/extendedproperties?draft={draft}", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("draft", draft);
		url.formatUrl("orderId", orderId);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def addExtendedProperties(self,extendedProperties, orderId, updateMode = None, version = None):
		"""
			orders-extendedproperties Post AddExtendedProperties description DOCUMENT_HERE 
			Request Params
				string orderId Unique identifier of the order.
				string updateMode Specifies whether to update the original order, update the order in draft mode, or update the order in draft mode and then commit the changes to the original. Draft mode enables users to make incremental order changes before committing the changes to the original order. Valid values are "ApplyToOriginal," "ApplyToDraft," or "ApplyAndCommit."
				string version Determines whether or not to check versioning of items for concurrency purposes.
				array|extendedProperties Mozu.CommerceRuntime.Contracts.Commerce.ExtendedProperty ApiType DOCUMENT_HERE 
			Response
				array|ExtendedProperty 
		"""

		url = MozuUrl("/api/commerce/orders/{orderId}/extendedproperties?updatemode={updateMode}&version={version}", "POST", UrlLocation.TenantPod, False);
		url.formatUrl("orderId", orderId);
		url.formatUrl("updateMode", updateMode);
		url.formatUrl("version", version);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def updateExtendedProperty(self,extendedProperty, orderId, key, updateMode = None, version = None, upsert = False, responseFields = None):
		"""
			orders-extendedproperties Put UpdateExtendedProperty description DOCUMENT_HERE 
			Request Params
				string key 
				string orderId Unique identifier of the order.
				string responseFields A list or array of fields returned for a call. These fields may be customized and may be used for various types of data calls in Mozu. For example, responseFields are returned for retrieving or updating attributes, carts, and messages in Mozu.
				string updateMode Specifies whether to update the original order, update the order in draft mode, or update the order in draft mode and then commit the changes to the original. Draft mode enables users to make incremental order changes before committing the changes to the original order. Valid values are "ApplyToOriginal," "ApplyToDraft," or "ApplyAndCommit."
				bool upsert 
				string version Determines whether or not to check versioning of items for concurrency purposes.
				extendedProperty Mozu.CommerceRuntime.Contracts.Commerce.ExtendedProperty ApiType DOCUMENT_HERE 
			Response
				ExtendedProperty 
		"""

		url = MozuUrl("/api/commerce/orders/{orderId}/extendedproperties/{key}?updatemode={updateMode}&version={version}&upsert={upsert}&responseFields={responseFields}", "PUT", UrlLocation.TenantPod, False);
		url.formatUrl("key", key);
		url.formatUrl("orderId", orderId);
		url.formatUrl("responseFields", responseFields);
		url.formatUrl("updateMode", updateMode);
		url.formatUrl("upsert", upsert);
		url.formatUrl("version", version);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def updateExtendedProperties(self,extendedProperties, orderId, updateMode = None, version = None, upsert = False):
		"""
			orders-extendedproperties Put UpdateExtendedProperties description DOCUMENT_HERE 
			Request Params
				string orderId Unique identifier of the order.
				string updateMode Specifies whether to update the original order, update the order in draft mode, or update the order in draft mode and then commit the changes to the original. Draft mode enables users to make incremental order changes before committing the changes to the original order. Valid values are "ApplyToOriginal," "ApplyToDraft," or "ApplyAndCommit."
				bool upsert 
				string version Determines whether or not to check versioning of items for concurrency purposes.
				array|extendedProperties Mozu.CommerceRuntime.Contracts.Commerce.ExtendedProperty ApiType DOCUMENT_HERE 
			Response
				array|ExtendedProperty 
		"""

		url = MozuUrl("/api/commerce/orders/{orderId}/extendedproperties?updatemode={updateMode}&version={version}&upsert={upsert}", "PUT", UrlLocation.TenantPod, False);
		url.formatUrl("orderId", orderId);
		url.formatUrl("updateMode", updateMode);
		url.formatUrl("upsert", upsert);
		url.formatUrl("version", version);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def deleteExtendedProperty(self,orderId, key, updateMode = None, version = None):
		"""
			orders-extendedproperties Delete DeleteExtendedProperty description DOCUMENT_HERE 
			Request Params
				string key 
				string orderId Unique identifier of the order.
				string updateMode Specifies whether to update the original order, update the order in draft mode, or update the order in draft mode and then commit the changes to the original. Draft mode enables users to make incremental order changes before committing the changes to the original order. Valid values are "ApplyToOriginal," "ApplyToDraft," or "ApplyAndCommit."
				string version Determines whether or not to check versioning of items for concurrency purposes.
			Response
		"""

		url = MozuUrl("/api/commerce/orders/{orderId}/extendedproperties/{key}?updatemode={updateMode}&version={version}", "DELETE", UrlLocation.TenantPod, False);
		url.formatUrl("key", key);
		url.formatUrl("orderId", orderId);
		url.formatUrl("updateMode", updateMode);
		url.formatUrl("version", version);
		self.client.withResourceUrl(url).execute();

	
		
	def deleteExtendedProperties(self,keys, orderId, updateMode = None, version = None):
		"""
			orders-extendedproperties Delete DeleteExtendedProperties description DOCUMENT_HERE 
			Request Params
				string orderId Unique identifier of the order.
				string updateMode Specifies whether to update the original order, update the order in draft mode, or update the order in draft mode and then commit the changes to the original. Draft mode enables users to make incremental order changes before committing the changes to the original order. Valid values are "ApplyToOriginal," "ApplyToDraft," or "ApplyAndCommit."
				string version Determines whether or not to check versioning of items for concurrency purposes.
				array|keys 
			Response
		"""

		url = MozuUrl("/api/commerce/orders/{orderId}/extendedproperties?updatemode={updateMode}&version={version}", "DELETE", UrlLocation.TenantPod, False);
		url.formatUrl("orderId", orderId);
		url.formatUrl("updateMode", updateMode);
		url.formatUrl("version", version);
		self.client.withResourceUrl(url).execute();

	
	
	