
"""
    This code was generated by Codezu.     

    Changes to this file may cause incorrect behavior and will be lost if
    the code is regenerated.
"""


from mozurestsdk.mozuclient import default as default_client
from mozurestsdk.mozuurl import MozuUrl;
from mozurestsdk.urllocation import UrlLocation
from mozurestsdk.apicontext import ApiContext;

class Package(object):
	def __init__(self, apiContext: ApiContext = None, mozuClient = None):
		self.client = mozuClient or default_client();
		if (apiContext is not None):
			self.client.withApiContext(apiContext);
		else:
			self.client.withApiContext(ApiContext());
	
	def getAvailablePackageFulfillmentActions(self,orderId, packageId):
		""" 
		
		Args:
			| orderId (string) - Unique identifier of the order.
			| packageId (string) - Unique identifier of the package for which to retrieve the label.
		
		Returns:
			| array of string 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/orders/{orderId}/packages/{packageId}/actions", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("orderId", orderId);
		url.formatUrl("packageId", packageId);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getPackageLabel(self,orderId, packageId):
		""" 
		
		Args:
			| orderId (string) - Unique identifier of the order.
			| packageId (string) - Unique identifier of the package for which to retrieve the label.
		
		Returns:
			| Stream 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/orders/{orderId}/packages/{packageId}/label", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("orderId", orderId);
		url.formatUrl("packageId", packageId);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getPackage(self,orderId, packageId, responseFields = None):
		""" 
		
		Args:
			| orderId (string) - Unique identifier of the order.
			| packageId (string) - Unique identifier of the package for which to retrieve the label.
			| responseFields (string) - Filtering syntax appended to an API call to increase or decrease the amount of data returned inside a JSON object. This parameter should only be used to retrieve data. Attempting to update data using this parameter may cause data loss.
		
		Returns:
			| Package 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/orders/{orderId}/packages/{packageId}?responseFields={responseFields}", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("orderId", orderId);
		url.formatUrl("packageId", packageId);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def createPackage(self,package, orderId, responseFields = None):
		""" 
		
		Args:
			| package(package) - Properties of a physical package shipped for an order.
			| orderId (string) - Unique identifier of the order.
			| responseFields (string) - Filtering syntax appended to an API call to increase or decrease the amount of data returned inside a JSON object. This parameter should only be used to retrieve data. Attempting to update data using this parameter may cause data loss.
		
		Returns:
			| Package 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/orders/{orderId}/packages?responseFields={responseFields}", "POST", UrlLocation.TenantPod, False);
		url.formatUrl("orderId", orderId);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).withBody(package).execute();
		return self.client.result();

	
		
	def updatePackage(self,package, orderId, packageId, responseFields = None):
		""" 
		
		Args:
			| package(package) - Properties of a physical package shipped for an order.
			| orderId (string) - Unique identifier of the order.
			| packageId (string) - Unique identifier of the package for which to retrieve the label.
			| responseFields (string) - Filtering syntax appended to an API call to increase or decrease the amount of data returned inside a JSON object. This parameter should only be used to retrieve data. Attempting to update data using this parameter may cause data loss.
		
		Returns:
			| Package 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/orders/{orderId}/packages/{packageId}?responseFields={responseFields}", "PUT", UrlLocation.TenantPod, False);
		url.formatUrl("orderId", orderId);
		url.formatUrl("packageId", packageId);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).withBody(package).execute();
		return self.client.result();

	
		
	def deletePackage(self,orderId, packageId):
		""" 
		
		Args:
			| orderId (string) - Unique identifier of the order.
			| packageId (string) - Unique identifier of the package for which to retrieve the label.
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/orders/{orderId}/packages/{packageId}", "DELETE", UrlLocation.TenantPod, False);
		url.formatUrl("orderId", orderId);
		url.formatUrl("packageId", packageId);
		self.client.withResourceUrl(url).execute();

	
	
	