
"""
    This code was generated by Codezu.     

    Changes to this file may cause incorrect behavior and will be lost if
    the code is regenerated.
"""


from mozurestsdk.mozuclient import default as default_client
from mozurestsdk.mozuurl import MozuUrl;
from mozurestsdk.urllocation import UrlLocation
from mozurestsdk.apicontext import ApiContext;

class Payment(object):
	def __init__(self, apiContext: ApiContext = None, mozuClient = None):
		self.client = mozuClient or default_client();
		client.withApiContext(apiContext);
	
	def getPayments(self,orderId, responseFields = None):
		"""
			Retrieves information about all payment transactions submitted for the specified order.
			Request Params
				string orderId Unique identifier of the order.
				string responseFields Use this field to include those fields which are not included by default.
			Response
				PaymentCollection 
		"""

		url = MozuUrl("/api/commerce/orders/{orderId}/payments/?responseFields={responseFields}", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("orderId", orderId);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getAvailablePaymentActions(self,orderId, paymentId):
		"""
			Retrieves the list of all available payment actions dependent on the order payment status by specifying the order ID.
			Request Params
				string orderId Unique identifier of the order.
				string paymentId Unique identifier of the payment for which to perform the action.
			Response
				array|string 
		"""

		url = MozuUrl("/api/commerce/orders/{orderId}/payments/{paymentId}/actions", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("orderId", orderId);
		url.formatUrl("paymentId", paymentId);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getPayment(self,orderId, paymentId, responseFields = None):
		"""
			Retrieves information about a specific payment transaction submitted for the specified order.
			Request Params
				string orderId Unique identifier of the order.
				string paymentId Unique identifier of the payment for which to perform the action.
				string responseFields Use this field to include those fields which are not included by default.
			Response
				Payment 
		"""

		url = MozuUrl("/api/commerce/orders/{orderId}/payments/{paymentId}?responseFields={responseFields}", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("orderId", orderId);
		url.formatUrl("paymentId", paymentId);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def performPaymentAction(self,action, orderId, paymentId, responseFields = None):
		"""
			Performs the specified action for an individual order payment transaction.
			Request Params
				string orderId Unique identifier of the order.
				string paymentId Unique identifier of the payment for which to perform the action.
				string responseFields Use this field to include those fields which are not included by default.
				action Properties of the payment action performed for an order.
			Response
				Order 
		"""

		url = MozuUrl("/api/commerce/orders/{orderId}/payments/{paymentId}/actions?responseFields={responseFields}", "POST", UrlLocation.TenantPod, False);
		url.formatUrl("orderId", orderId);
		url.formatUrl("paymentId", paymentId);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).withBody(action).execute();
		return self.client.result();

	
		
	def createPaymentAction(self,action, orderId, responseFields = None):
		"""
			Creates a new payment transaction for the specified order and performs the specified action.
			Request Params
				string orderId Unique identifier of the order.
				string responseFields Use this field to include those fields which are not included by default.
				action Properties of the payment action performed for an order.
			Response
				Order 
		"""

		url = MozuUrl("/api/commerce/orders/{orderId}/payments/actions?responseFields={responseFields}", "POST", UrlLocation.TenantPod, False);
		url.formatUrl("orderId", orderId);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).withBody(action).execute();
		return self.client.result();

	
	
	