
"""
    This code was generated by Codezu.     

    Changes to this file may cause incorrect behavior and will be lost if
    the code is regenerated.
"""


from mozurestsdk.mozuclient import default as default_client
from mozurestsdk.mozuurl import MozuUrl;
from mozurestsdk.urllocation import UrlLocation
from mozurestsdk.apicontext import ApiContext;

class Pickup(object):
	def __init__(self, apiContext: ApiContext = None, mozuClient = None):
		self.client = mozuClient or default_client();
		if (apiContext is not None):
			self.client.withApiContext(apiContext);
		else:
			self.client.withApiContext(ApiContext());
	
	def getAvailablePickupFulfillmentActions(self,orderId, pickupId):
		""" 
		
		Args:
			| orderId (string) - Unique identifier of the order.
			| pickupId (string) - Unique identifier of the pickup to remove.
		
		Returns:
			| array of string 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/orders/{orderId}/pickups/{pickupId}/actions", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("orderId", orderId);
		url.formatUrl("pickupId", pickupId);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getPickup(self,orderId, pickupId, responseFields = None):
		""" 
		
		Args:
			| orderId (string) - Unique identifier of the order.
			| pickupId (string) - Unique identifier of the pickup to remove.
			| responseFields (string) - Filtering syntax appended to an API call to increase or decrease the amount of data returned inside a JSON object. This parameter should only be used to retrieve data. Attempting to update data using this parameter may cause data loss.
		
		Returns:
			| Pickup 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/orders/{orderId}/pickups/{pickupId}?responseFields={responseFields}", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("orderId", orderId);
		url.formatUrl("pickupId", pickupId);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def createPickup(self,pickup, orderId, responseFields = None):
		""" 
		
		Args:
			| pickup(pickup) - Properties of an in-store pickup defined to fulfill items in an order.
			| orderId (string) - Unique identifier of the order.
			| responseFields (string) - Filtering syntax appended to an API call to increase or decrease the amount of data returned inside a JSON object. This parameter should only be used to retrieve data. Attempting to update data using this parameter may cause data loss.
		
		Returns:
			| Pickup 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/orders/{orderId}/pickups?responseFields={responseFields}", "POST", UrlLocation.TenantPod, False);
		url.formatUrl("orderId", orderId);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).withBody(pickup).execute();
		return self.client.result();

	
		
	def updatePickup(self,pickup, orderId, pickupId, responseFields = None):
		""" 
		
		Args:
			| pickup(pickup) - Properties of an in-store pickup defined to fulfill items in an order.
			| orderId (string) - Unique identifier of the order.
			| pickupId (string) - Unique identifier of the pickup to remove.
			| responseFields (string) - Filtering syntax appended to an API call to increase or decrease the amount of data returned inside a JSON object. This parameter should only be used to retrieve data. Attempting to update data using this parameter may cause data loss.
		
		Returns:
			| Pickup 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/orders/{orderId}/pickups/{pickupId}?responseFields={responseFields}", "PUT", UrlLocation.TenantPod, False);
		url.formatUrl("orderId", orderId);
		url.formatUrl("pickupId", pickupId);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).withBody(pickup).execute();
		return self.client.result();

	
		
	def deletePickup(self,orderId, pickupId):
		""" 
		
		Args:
			| orderId (string) - Unique identifier of the order.
			| pickupId (string) - Unique identifier of the pickup to remove.
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/orders/{orderId}/pickups/{pickupId}", "DELETE", UrlLocation.TenantPod, False);
		url.formatUrl("orderId", orderId);
		url.formatUrl("pickupId", pickupId);
		self.client.withResourceUrl(url).execute();

	
	
	