
"""
    This code was generated by Codezu.     

    Changes to this file may cause incorrect behavior and will be lost if
    the code is regenerated.
"""


from mozurestsdk.mozuclient import default as default_client
from mozurestsdk.mozuurl import MozuUrl;
from mozurestsdk.urllocation import UrlLocation
from mozurestsdk.apicontext import ApiContext;

class AttributeVocabularyValue(object):
	def __init__(self, apiContext: ApiContext = None, mozuClient = None):
		self.client = mozuClient or default_client();
		if (apiContext is not None):
			self.client.withApiContext(apiContext);
		else:
			self.client.withApiContext(ApiContext());
	
	def getAttributeVocabularyValues(self,attributeFQN):
		""" 
		
		Args:
			| attributeFQN (string) - 
		
		Returns:
			| array of AttributeVocabularyValue 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/catalog/admin/attributedefinition/attributes/{attributeFQN}/VocabularyValues", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("attributeFQN", attributeFQN);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getAttributeVocabularyValueLocalizedContents(self,attributeFQN, value):
		""" 
		
		Args:
			| attributeFQN (string) - 
			| value (string) - 
		
		Returns:
			| array of AttributeVocabularyValueLocalizedContent 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/catalog/admin/attributedefinition/attributes/{attributeFQN}/VocabularyValues/{value}/LocalizedContent", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("attributeFQN", attributeFQN);
		url.formatUrl("value", value);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getAttributeVocabularyValueLocalizedContent(self,attributeFQN, value, localeCode, responseFields = None):
		""" 
		
		Args:
			| attributeFQN (string) - 
			| value (string) - 
			| localeCode (string) - 
			| responseFields (string) - 
		
		Returns:
			| AttributeVocabularyValueLocalizedContent 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/catalog/admin/attributedefinition/attributes/{attributeFQN}/VocabularyValues/{value}/LocalizedContent/{localeCode}?responseFields={responseFields}", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("attributeFQN", attributeFQN);
		url.formatUrl("localeCode", localeCode);
		url.formatUrl("responseFields", responseFields);
		url.formatUrl("value", value);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getAttributeVocabularyValue(self,attributeFQN, value, responseFields = None):
		""" 
		
		Args:
			| attributeFQN (string) - 
			| value (string) - The actual unique value of the attribute vocabulary to retrieve. A single attribute must have a unique value and match the attribute's data type. If a string value returns null, the system will generate a value. The actual string content displayed shoud be stored as "Content" and actual content is required for string values.
			| responseFields (string) - 
		
		Returns:
			| AttributeVocabularyValue 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/catalog/admin/attributedefinition/attributes/{attributeFQN}/VocabularyValues/{value}?responseFields={responseFields}", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("attributeFQN", attributeFQN);
		url.formatUrl("responseFields", responseFields);
		url.formatUrl("value", value);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def addAttributeVocabularyValueLocalizedContent(self,localizedContent, attributeFQN, value, responseFields = None):
		""" 
		
		Args:
			| localizedContent(localizedContent) - 
			| attributeFQN (string) - 
			| value (string) - 
			| responseFields (string) - 
		
		Returns:
			| AttributeVocabularyValueLocalizedContent 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/catalog/admin/attributedefinition/attributes/{attributeFQN}/VocabularyValues/{value}/localizedContent?responseFields={responseFields}", "POST", UrlLocation.TenantPod, False);
		url.formatUrl("attributeFQN", attributeFQN);
		url.formatUrl("responseFields", responseFields);
		url.formatUrl("value", value);
		self.client.withResourceUrl(url).withBody(localizedContent).execute();
		return self.client.result();

	
		
	def addAttributeVocabularyValue(self,attributeVocabularyValue, attributeFQN, responseFields = None):
		""" 
		
		Args:
			| attributeVocabularyValue(attributeVocabularyValue) - The predefined vocabulary value to add to the attribute content.
			| attributeFQN (string) - 
			| responseFields (string) - 
		
		Returns:
			| AttributeVocabularyValue 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/catalog/admin/attributedefinition/attributes/{attributeFQN}/VocabularyValues?responseFields={responseFields}", "POST", UrlLocation.TenantPod, False);
		url.formatUrl("attributeFQN", attributeFQN);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).withBody(attributeVocabularyValue).execute();
		return self.client.result();

	
		
	def updateAttributeVocabularyValues(self,vocabularyValues, attributeFQN):
		""" 
		
		Args:
			| vocabularyValues(array|vocabularyValues) - The actual vocabulary values for the attribute being updated.
			| attributeFQN (string) - 
		
		Returns:
			| array of AttributeVocabularyValue 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/catalog/admin/attributedefinition/attributes/{attributeFQN}/VocabularyValues", "PUT", UrlLocation.TenantPod, False);
		url.formatUrl("attributeFQN", attributeFQN);
		self.client.withResourceUrl(url).withBody(vocabularyValues).execute();
		return self.client.result();

	
		
	def updateAttributeVocabularyValueLocalizedContents(self,localizedContent, attributeFQN, value):
		""" 
		
		Args:
			| localizedContent(array|localizedContent) - 
			| attributeFQN (string) - 
			| value (string) - 
		
		Returns:
			| array of AttributeVocabularyValueLocalizedContent 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/catalog/admin/attributedefinition/attributes/{attributeFQN}/VocabularyValues/{value}/LocalizedContent", "PUT", UrlLocation.TenantPod, False);
		url.formatUrl("attributeFQN", attributeFQN);
		url.formatUrl("value", value);
		self.client.withResourceUrl(url).withBody(localizedContent).execute();
		return self.client.result();

	
		
	def updateAttributeVocabularyValueLocalizedContent(self,localizedContent, attributeFQN, value, localeCode, responseFields = None):
		""" 
		
		Args:
			| localizedContent(localizedContent) - 
			| attributeFQN (string) - 
			| value (string) - 
			| localeCode (string) - 
			| responseFields (string) - 
		
		Returns:
			| AttributeVocabularyValueLocalizedContent 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/catalog/admin/attributedefinition/attributes/{attributeFQN}/VocabularyValues/{value}/LocalizedContent/{localeCode}?responseFields={responseFields}", "PUT", UrlLocation.TenantPod, False);
		url.formatUrl("attributeFQN", attributeFQN);
		url.formatUrl("localeCode", localeCode);
		url.formatUrl("responseFields", responseFields);
		url.formatUrl("value", value);
		self.client.withResourceUrl(url).withBody(localizedContent).execute();
		return self.client.result();

	
		
	def updateAttributeVocabularyValue(self,attributeVocabularyValue, attributeFQN, value, responseFields = None):
		""" 
		
		Args:
			| attributeVocabularyValue(attributeVocabularyValue) - The predefined vocabulary value to add to the attribute content to update.
			| attributeFQN (string) - 
			| value (string) - The actual unique value of the attribute vocabulary value to update. A single attribute must have a unique value and match the attribute's data type. If a string value returns null, the system will generate a value. The actual string content displayed shoud be stored as "Content" and actual content is required for string values.
			| responseFields (string) - 
		
		Returns:
			| AttributeVocabularyValue 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/catalog/admin/attributedefinition/attributes/{attributeFQN}/VocabularyValues/{value}?responseFields={responseFields}", "PUT", UrlLocation.TenantPod, False);
		url.formatUrl("attributeFQN", attributeFQN);
		url.formatUrl("responseFields", responseFields);
		url.formatUrl("value", value);
		self.client.withResourceUrl(url).withBody(attributeVocabularyValue).execute();
		return self.client.result();

	
		
	def deleteAttributeVocabularyValue(self,attributeFQN, value):
		""" 
		
		Args:
			| attributeFQN (string) - 
			| value (string) - The actual unique value of the attribute vocabulary to delete. A single attribute must have a unique value and match the attribute's data type. If a string value returns null, the system will generate a value. The actual string content displayed shoud be stored as "Content" and actual content is required for string values.
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/catalog/admin/attributedefinition/attributes/{attributeFQN}/VocabularyValues/{value}", "DELETE", UrlLocation.TenantPod, False);
		url.formatUrl("attributeFQN", attributeFQN);
		url.formatUrl("value", value);
		self.client.withResourceUrl(url).execute();

	
		
	def deleteAttributeVocabularyValueLocalizedContent(self,attributeFQN, value, localeCode):
		""" 
		
		Args:
			| attributeFQN (string) - 
			| value (string) - 
			| localeCode (string) - 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/catalog/admin/attributedefinition/attributes/{attributeFQN}/VocabularyValues/{value}/LocalizedContent/{localeCode}", "DELETE", UrlLocation.TenantPod, False);
		url.formatUrl("attributeFQN", attributeFQN);
		url.formatUrl("localeCode", localeCode);
		url.formatUrl("value", value);
		self.client.withResourceUrl(url).execute();

	
	
	