
"""
    This code was generated by Codezu.     

    Changes to this file may cause incorrect behavior and will be lost if
    the code is regenerated.
"""


from mozurestsdk.mozuclient import default as default_client
from mozurestsdk.mozuurl import MozuUrl;
from mozurestsdk.urllocation import UrlLocation
from mozurestsdk.apicontext import ApiContext;

class PropertyType(object):
	def __init__(self, apiContext: ApiContext = None, dataViewMode="Live", mozuClient = None):
		if (apiContext is not None and apiContext.dataViewMode is None):
			apiContext.dataViewMode = dataViewMode;
		else:
			apiContext = ApiContext(dataViewMode = dataViewMode);
		self.client = mozuClient or default_client();
		self.client.withApiContext(apiContext);
	
	def getPropertyTypes(self,pageSize = None, startIndex = None, responseFields = None):
		""" 
		
		Args:
			| pageSize (int) - When creating paged results from a query, this value indicates the zero-based offset in the complete result set where the returned entities begin. For example, with this parameter set to 25, to get the 51st through the 75th items, set startIndex to 50.
			| startIndex (int) - When creating paged results from a query, this value indicates the zero-based offset in the complete result set where the returned entities begin. For example, with pageSize set to 25, to get the 51st through the 75th items, set this parameter to 50.
			| responseFields (string) - Filtering syntax appended to an API call to increase or decrease the amount of data returned inside a JSON object. This parameter should only be used to retrieve data. Attempting to update data using this parameter may cause data loss.
		
		Returns:
			| PropertyTypeCollection 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/content/propertytypes/?pageSize={pageSize}&startIndex={startIndex}&responseFields={responseFields}", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("pageSize", pageSize);
		url.formatUrl("responseFields", responseFields);
		url.formatUrl("startIndex", startIndex);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getPropertyType(self,propertyTypeName, responseFields = None):
		""" 
		
		Args:
			| propertyTypeName (string) - The name of the property type.
			| responseFields (string) - Filtering syntax appended to an API call to increase or decrease the amount of data returned inside a JSON object. This parameter should only be used to retrieve data. Attempting to update data using this parameter may cause data loss.
		
		Returns:
			| PropertyType 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/content/propertytypes/{propertyTypeName}?responseFields={responseFields}", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("propertyTypeName", propertyTypeName);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def createPropertyType(self,propertyType, responseFields = None):
		""" 
		
		Args:
			| propertyType(propertyType) - Property type available for content. Property types are like templates that can be reused.
			| responseFields (string) - Filtering syntax appended to an API call to increase or decrease the amount of data returned inside a JSON object. This parameter should only be used to retrieve data. Attempting to update data using this parameter may cause data loss.
		
		Returns:
			| PropertyType 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/content/propertytypes/?responseFields={responseFields}", "POST", UrlLocation.TenantPod, False);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).withBody(propertyType).execute();
		return self.client.result();

	
		
	def updatePropertyType(self,propertyType, propertyTypeName, responseFields = None):
		""" 
		
		Args:
			| propertyType(propertyType) - Property type available for content. Property types are like templates that can be reused.
			| propertyTypeName (string) - The name of the property type.
			| responseFields (string) - Filtering syntax appended to an API call to increase or decrease the amount of data returned inside a JSON object. This parameter should only be used to retrieve data. Attempting to update data using this parameter may cause data loss.
		
		Returns:
			| PropertyType 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/content/propertytypes/{propertyTypeName}?responseFields={responseFields}", "PUT", UrlLocation.TenantPod, False);
		url.formatUrl("propertyTypeName", propertyTypeName);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).withBody(propertyType).execute();
		return self.client.result();

	
		
	def deletePropertyType(self,propertyTypeName):
		""" 
		
		Args:
			| propertyTypeName (string) - The name of the property type.
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/content/propertytypes/{propertyTypeName}", "DELETE", UrlLocation.TenantPod, False);
		url.formatUrl("propertyTypeName", propertyTypeName);
		self.client.withResourceUrl(url).execute();

	
	
	