
"""
    This code was generated by Codezu.     

    Changes to this file may cause incorrect behavior and will be lost if
    the code is regenerated.
"""


from mozurestsdk.mozuclient import default as default_client
from mozurestsdk.mozuurl import MozuUrl;
from mozurestsdk.urllocation import UrlLocation
from mozurestsdk.apicontext import ApiContext;

class PublishSetSummary(object):
	def __init__(self, apiContext: ApiContext = None, mozuClient = None):
		self.client = mozuClient or default_client();
		if (apiContext is not None):
			self.client.withApiContext(apiContext);
		else:
			self.client.withApiContext(ApiContext());
	
	def getPublishSets(self,pageSize = None, startIndex = None, responseFields = None):
		""" 
		
		Args:
			| pageSize (int) - 
			| startIndex (int) - 
			| responseFields (string) - 
		
		Returns:
			| PublishSetSummaryPagedCollection 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/content/publishsets/?pageSize={pageSize}&startIndex={startIndex}&responseFields={responseFields}", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("pageSize", pageSize);
		url.formatUrl("responseFields", responseFields);
		url.formatUrl("startIndex", startIndex);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getPublishSetItems(self,code, pageSize = None, startIndex = None, sortBy = None, filter = None, responseFields = None):
		""" 
		
		Args:
			| code (string) - 
			| pageSize (int) - 
			| startIndex (int) - 
			| sortBy (string) - 
			| filter (string) - 
			| responseFields (string) - 
		
		Returns:
			| DocumentDraftSummaryPagedCollection 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/content/publishsets/{code}/items?pageSize={pageSize}&startIndex={startIndex}&sortBy={sortBy}&filter={filter}&responseFields={responseFields}", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("code", code);
		url.formatUrl("filter", filter);
		url.formatUrl("pageSize", pageSize);
		url.formatUrl("responseFields", responseFields);
		url.formatUrl("sortBy", sortBy);
		url.formatUrl("startIndex", startIndex);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def deletePublishSet(self,code, shouldDiscard = False, responseFields = None):
		""" 
		
		Args:
			| code (string) - 
			| shouldDiscard (bool) - 
			| responseFields (string) - 
		
		Returns:
			| object 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/content/publishsets/{code}?shouldDiscard={shouldDiscard}&responseFields={responseFields}", "POST", UrlLocation.TenantPod, False);
		url.formatUrl("code", code);
		url.formatUrl("responseFields", responseFields);
		url.formatUrl("shouldDiscard", shouldDiscard);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def addPublishSetItems(self,itemsToPublish, code, responseFields = None):
		""" 
		
		Args:
			| itemsToPublish(array|itemsToPublish) - 
			| code (string) - 
			| responseFields (string) - 
		
		Returns:
			| object 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/content/publishsets/{code}/items?responseFields={responseFields}", "PUT", UrlLocation.TenantPod, False);
		url.formatUrl("code", code);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).withBody(itemsToPublish).execute();
		return self.client.result();

	
	
	