
"""
    This code was generated by Codezu.     

    Changes to this file may cause incorrect behavior and will be lost if
    the code is regenerated.
"""


from mozurestsdk.mozuclient import default as default_client
from mozurestsdk.mozuurl import MozuUrl;
from mozurestsdk.urllocation import UrlLocation
from mozurestsdk.apicontext import ApiContext;

class EventDeliverySummary(object):
	def __init__(self, apiContext: ApiContext = None, mozuClient = None):
		self.client = mozuClient or default_client();
		client.withApiContext(apiContext);
	
	def getDeliveryAttemptSummary(self,subscriptionId, id = None, responseFields = None):
		"""
			This operation method is the external/public event entity used specifically in pull/poll event scenarios.
			Request Params
				int id Unique identifier of the customer segment to retrieve.
				string responseFields Use this field to include those fields which are not included by default.
				string subscriptionId Unique identifier for a subscription, such as subscribing tenants for an event or to receive a notification.
			Response
				EventDeliverySummary 
		"""

		url = MozuUrl("/api/event/push/subscriptions/{subscriptionId}/deliveryattempts/{id}?responseFields={responseFields}", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("id", id);
		url.formatUrl("responseFields", responseFields);
		url.formatUrl("subscriptionId", subscriptionId);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getDeliveryAttemptSummaries(self,subscriptionId, startIndex = None, pageSize = None, sortBy = None, filter = None, responseFields = None):
		"""
			Retrieves a collection of data for delivery attempts of events and notifications. These are notifications sent to subscribing sites and tenants. A paged list is returned sorted and filtered per the entered parameters.
			Request Params
				string filter A set of expressions that consist of a field, operator, and value and represent search parameter syntax when filtering results of a query. Valid operators include equals (eq), does not equal (ne), greater than (gt), less than (lt), greater than or equal to (ge), less than or equal to (le), starts with (sw), or contains (cont). For example - "filter=IsDisplayed+eq+true"
				int pageSize The number of results to display on each page when creating paged results from a query. The amount is divided and displayed on the `pageCount `amount of pages. The default is 20 and maximum value is 200 per page.
				string responseFields Use this field to include those fields which are not included by default.
				string sortBy The element to sort the results by and the channel in which the results appear. Either ascending (a-z) or descending (z-a) channel. Optional.
				int startIndex When creating paged results from a query, this value indicates the zero-based offset in the complete result set where the returned entities begin. For example, with a `pageSize `of 25, to get the 51st through the 75th items, use `startIndex=3`.
				string subscriptionId Unique identifier for a subscription, such as subscribing tenants for an event or to receive a notification.
			Response
				EventDeliverySummaryCollection 
		"""

		url = MozuUrl("/api/event/push/subscriptions/{subscriptionId}/deliveryattempts?startIndex={startIndex}&pageSize={pageSize}&sortBy={sortBy}&filter={filter}&responseFields={responseFields}", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("filter", filter);
		url.formatUrl("pageSize", pageSize);
		url.formatUrl("responseFields", responseFields);
		url.formatUrl("sortBy", sortBy);
		url.formatUrl("startIndex", startIndex);
		url.formatUrl("subscriptionId", subscriptionId);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
	
	