
"""
    This code was generated by Codezu.     

    Changes to this file may cause incorrect behavior and will be lost if
    the code is regenerated.
"""


from mozurestsdk.mozuclient import default as default_client
from mozurestsdk.mozuurl import MozuUrl;
from mozurestsdk.urllocation import UrlLocation
from mozurestsdk.apicontext import ApiContext;

class CartItem(object):
	def __init__(self, apiContext: ApiContext = None, mozuClient = None):
		self.client = mozuClient or default_client();
		if (apiContext is not None):
			self.client.withApiContext(apiContext);
		else:
			self.client.withApiContext(ApiContext());
	
	def getCartItem(self,cartItemId, responseFields = None):
		""" 
		
		Args:
			| cartItemId (string) - Identifier of the cart item to retrieve.
			| responseFields (string) - 
		
		Returns:
			| CartItem 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/carts/current/items/{cartItemId}?responseFields={responseFields}", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("cartItemId", cartItemId);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getCartItems(self,responseFields = None):
		""" 
		
		Args:
			| responseFields (string) - 
		
		Returns:
			| CartItemCollection 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/carts/current/items?responseFields={responseFields}", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def addItemToCart(self,cartItem, responseFields = None):
		""" 
		
		Args:
			| cartItem(cartItem) - All properties of the new cart item. The product code is required.
			| responseFields (string) - 
		
		Returns:
			| CartItem 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/carts/current/items?responseFields={responseFields}", "POST", UrlLocation.TenantPod, False);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).withBody(cartItem).execute();
		return self.client.result();

	
		
	def updateCartItemQuantity(self,cartItemId, quantity, responseFields = None):
		""" 
		
		Args:
			| cartItemId (string) - Identifier of the cart item to update quantity.
			| quantity (int) - The number of cart items in the shopper's active cart.
			| responseFields (string) - 
		
		Returns:
			| CartItem 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/carts/current/items/{cartItemId}/{quantity}?responseFields={responseFields}", "PUT", UrlLocation.TenantPod, False);
		url.formatUrl("cartItemId", cartItemId);
		url.formatUrl("quantity", quantity);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def updateCartItem(self,cartItem, cartItemId, responseFields = None):
		""" 
		
		Args:
			| cartItem(cartItem) - The properties of the cart item to update.
			| cartItemId (string) - Identifier of the cart item to update.
			| responseFields (string) - 
		
		Returns:
			| CartItem 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/carts/current/items/{cartItemId}?responseFields={responseFields}", "PUT", UrlLocation.TenantPod, False);
		url.formatUrl("cartItemId", cartItemId);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).withBody(cartItem).execute();
		return self.client.result();

	
		
	def removeAllCartItems(self,):
		""" 
		
		Returns:
			| Cart 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/carts/current/items", "DELETE", UrlLocation.TenantPod, False);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def deleteCartItem(self,cartItemId):
		""" 
		
		Args:
			| cartItemId (string) - Identifier of the cart item to delete.
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/carts/current/items/{cartItemId}", "DELETE", UrlLocation.TenantPod, False);
		url.formatUrl("cartItemId", cartItemId);
		self.client.withResourceUrl(url).execute();

	
	
	