
"""
    This code was generated by Codezu.     

    Changes to this file may cause incorrect behavior and will be lost if
    the code is regenerated.
"""


from mozurestsdk.mozuclient import default as default_client
from mozurestsdk.mozuurl import MozuUrl;
from mozurestsdk.urllocation import UrlLocation
from mozurestsdk.apicontext import ApiContext;

class MasterCatalog(object):
	def __init__(self, apiContext: ApiContext = None, mozuClient = None):
		self.client = mozuClient or default_client();
		if (apiContext is not None):
			self.client.withApiContext(apiContext);
		else:
			self.client.withApiContext(ApiContext());
	
	def getMasterCatalogs(self,responseFields = None):
		""" 
		
		Args:
			| responseFields (string) - 
		
		Returns:
			| MasterCatalogCollection 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/catalog/admin/mastercatalogs/?responseFields={responseFields}", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getMasterCatalog(self,masterCatalogId, responseFields = None):
		""" 
		
		Args:
			| masterCatalogId (int) - 
			| responseFields (string) - 
		
		Returns:
			| MasterCatalog 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/catalog/admin/mastercatalogs/{masterCatalogId}?responseFields={responseFields}", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("masterCatalogId", masterCatalogId);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def updateMasterCatalog(self,masterCatalog, masterCatalogId, responseFields = None):
		""" 
		
		Args:
			| masterCatalog(masterCatalog) - Properties of the master catalog to update, which consists of the product publishing mode. Possible values are "Pending" which saves product updates in draft mode until they are published, and "Live" which publishes all product changes immediately.
			| masterCatalogId (int) - 
			| responseFields (string) - 
		
		Returns:
			| MasterCatalog 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/catalog/admin/mastercatalogs/{masterCatalogId}?responseFields={responseFields}", "PUT", UrlLocation.TenantPod, False);
		url.formatUrl("masterCatalogId", masterCatalogId);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).withBody(masterCatalog).execute();
		return self.client.result();

	
	
	