
"""
    This code was generated by Codezu.     

    Changes to this file may cause incorrect behavior and will be lost if
    the code is regenerated.
"""


from mozurestsdk.mozuclient import default as default_client
from mozurestsdk.mozuurl import MozuUrl;
from mozurestsdk.urllocation import UrlLocation
from mozurestsdk.apicontext import ApiContext;

class ProductReservation(object):
	def __init__(self, apiContext: ApiContext = None, dataViewMode="Live", mozuClient = None):
		if (apiContext is not None and apiContext.dataViewMode is None):
			apiContext.dataViewMode = dataViewMode;
		else:
			apiContext = ApiContext(dataViewMode = dataViewMode);
		self.client = mozuClient or default_client();
		self.client.withApiContext(apiContext);
	
	def getProductReservations(self,startIndex = None, pageSize = None, sortBy = None, filter = None, responseFields = None):
		""" 
		
		Args:
			| startIndex (int) - When creating paged results from a query, this value indicates the zero-based offset in the complete result set where the returned entities begin. For example, with pageSize set to 25, to get the 51st through the 75th items, set this parameter to 50.
			| pageSize (int) - When creating paged results from a query, this value indicates the zero-based offset in the complete result set where the returned entities begin. For example, with this parameter set to 25, to get the 51st through the 75th items, set startIndex to 50.
			| sortBy (string) - The element to sort the results by and the channel in which the results appear. Either ascending (a-z) or descending (z-a) channel. Optional. Refer to [Sorting and Filtering](../../../../Developer/api-guides/sorting-filtering.htm) for more information.
			| filter (string) - A set of filter expressions representing the search parameters for a query. This parameter is optional. Refer to [Sorting and Filtering](../../../../Developer/api-guides/sorting-filtering.htm) for a list of supported filters.
			| responseFields (string) - Filtering syntax appended to an API call to increase or decrease the amount of data returned inside a JSON object. This parameter should only be used to retrieve data. Attempting to update data using this parameter may cause data loss.
		
		Returns:
			| ProductReservationCollection 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/catalog/admin/productreservations/?startIndex={startIndex}&pageSize={pageSize}&sortBy={sortBy}&filter={filter}&responseFields={responseFields}", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("filter", filter);
		url.formatUrl("pageSize", pageSize);
		url.formatUrl("responseFields", responseFields);
		url.formatUrl("sortBy", sortBy);
		url.formatUrl("startIndex", startIndex);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getProductReservation(self,productReservationId, responseFields = None):
		""" 
		
		Args:
			| productReservationId (int) - Unique identifier of the product reservation.
			| responseFields (string) - Filtering syntax appended to an API call to increase or decrease the amount of data returned inside a JSON object. This parameter should only be used to retrieve data. Attempting to update data using this parameter may cause data loss.
		
		Returns:
			| ProductReservation 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/catalog/admin/productreservations/{productReservationId}?responseFields={responseFields}", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("productReservationId", productReservationId);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def addProductReservations(self,productReservations, skipInventoryCheck = False):
		""" 
		
		Args:
			| productReservations(array|productReservations) - A hold placed on product inventory for a particular product so that the quantity specified is set aside and available for purchase during the ordering process.
			| skipInventoryCheck (bool) - If true, skip the process to validate inventory when creating this product reservation.
		
		Returns:
			| array of ProductReservation 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/catalog/admin/productreservations/?skipInventoryCheck={skipInventoryCheck}", "POST", UrlLocation.TenantPod, False);
		url.formatUrl("skipInventoryCheck", skipInventoryCheck);
		self.client.withResourceUrl(url).withBody(productReservations).execute();
		return self.client.result();

	
		
	def commitReservations(self,productReservations):
		""" 
		
		Args:
			| productReservations(array|productReservations) - A hold placed on product inventory for a particular product so that the quantity specified is set aside and available for purchase during the ordering process.
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/catalog/admin/productreservations/commit", "POST", UrlLocation.TenantPod, False);
		self.client.withResourceUrl(url).withBody(productReservations).execute();

	
		
	def updateProductReservations(self,productReservations, skipInventoryCheck = False):
		""" 
		
		Args:
			| productReservations(array|productReservations) - A hold placed on product inventory for a particular product so that the quantity specified is set aside and available for purchase during the ordering process.
			| skipInventoryCheck (bool) - If true, skip the process to validate inventory when creating this product reservation.
		
		Returns:
			| array of ProductReservation 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/catalog/admin/productreservations/?skipInventoryCheck={skipInventoryCheck}", "PUT", UrlLocation.TenantPod, False);
		url.formatUrl("skipInventoryCheck", skipInventoryCheck);
		self.client.withResourceUrl(url).withBody(productReservations).execute();
		return self.client.result();

	
		
	def deleteProductReservation(self,productReservationId):
		""" 
		
		Args:
			| productReservationId (int) - Unique identifier of the product reservation.
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/catalog/admin/productreservations/{productReservationId}", "DELETE", UrlLocation.TenantPod, False);
		url.formatUrl("productReservationId", productReservationId);
		self.client.withResourceUrl(url).execute();

	
	
	