
"""
    This code was generated by Codezu.     

    Changes to this file may cause incorrect behavior and will be lost if
    the code is regenerated.
"""


from mozurestsdk.mozuclient import default as default_client
from mozurestsdk.mozuurl import MozuUrl;
from mozurestsdk.urllocation import UrlLocation
from mozurestsdk.apicontext import ApiContext;

class Search(object):
	def __init__(self, apiContext: ApiContext = None, mozuClient = None):
		self.client = mozuClient or default_client();
		if (apiContext is not None):
			self.client.withApiContext(apiContext);
		else:
			self.client.withApiContext(ApiContext());
	
	def getSearchTuningRule(self,searchTuningRuleCode, responseFields = None):
		""" 
		
		Args:
			| searchTuningRuleCode (string) - 
			| responseFields (string) - 
		
		Returns:
			| SearchTuningRule 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/catalog/admin/search/searchtuningrules/{searchTuningRuleCode}?responseFields={responseFields}", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("responseFields", responseFields);
		url.formatUrl("searchTuningRuleCode", searchTuningRuleCode);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getSearchTuningRules(self,startIndex = None, pageSize = None, sortBy = None, filter = None, responseFields = None):
		""" 
		
		Args:
			| startIndex (int) - 
			| pageSize (int) - 
			| sortBy (string) - 
			| filter (string) - 
			| responseFields (string) - 
		
		Returns:
			| SearchTuningRuleCollection 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/catalog/admin/search/searchtuningrules?startIndex={startIndex}&pageSize={pageSize}&sortBy={sortBy}&filter={filter}&responseFields={responseFields}", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("filter", filter);
		url.formatUrl("pageSize", pageSize);
		url.formatUrl("responseFields", responseFields);
		url.formatUrl("sortBy", sortBy);
		url.formatUrl("startIndex", startIndex);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getSearchTuningRuleSortFields(self,responseFields = None):
		""" 
		
		Args:
			| responseFields (string) - 
		
		Returns:
			| SearchTuningRuleSortFields 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/catalog/admin/search/searchtuningrulesortfields?responseFields={responseFields}", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getSettings(self,responseFields = None):
		""" 
		
		Args:
			| responseFields (string) - 
		
		Returns:
			| SearchSettings 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/catalog/admin/search/settings?responseFields={responseFields}", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getSynonymDefinitionCollection(self,localeCode, responseFields = None):
		""" 
		
		Args:
			| localeCode (string) - 
			| responseFields (string) - 
		
		Returns:
			| SynonymDefinitionCollection 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/catalog/admin/search/synonym-definitions/{localeCode}?responseFields={responseFields}", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("localeCode", localeCode);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getSynonymDefinitions(self,startIndex = None, pageSize = None, sortBy = None, filter = None, responseFields = None):
		""" 
		
		Args:
			| startIndex (int) - 
			| pageSize (int) - 
			| sortBy (string) - 
			| filter (string) - 
			| responseFields (string) - 
		
		Returns:
			| SynonymDefinitionPagedCollection 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/catalog/admin/search/synonyms/?startIndex={startIndex}&pageSize={pageSize}&sortBy={sortBy}&filter={filter}&responseFields={responseFields}", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("filter", filter);
		url.formatUrl("pageSize", pageSize);
		url.formatUrl("responseFields", responseFields);
		url.formatUrl("sortBy", sortBy);
		url.formatUrl("startIndex", startIndex);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getSynonymDefinition(self,synonymId, responseFields = None):
		""" 
		
		Args:
			| synonymId (int) - 
			| responseFields (string) - 
		
		Returns:
			| SynonymDefinition 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/catalog/admin/search/synonyms/{synonymId}?responseFields={responseFields}", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("responseFields", responseFields);
		url.formatUrl("synonymId", synonymId);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def addSearchTuningRule(self,searchTuningRuleIn, responseFields = None):
		""" 
		
		Args:
			| searchTuningRuleIn(searchTuningRuleIn) - 
			| responseFields (string) - 
		
		Returns:
			| SearchTuningRule 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/catalog/admin/search/searchtuningrules?responseFields={responseFields}", "POST", UrlLocation.TenantPod, False);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).withBody(searchTuningRuleIn).execute();
		return self.client.result();

	
		
	def updateSearchTuningRuleSortFields(self,searchTuningRuleSortFieldsIn, responseFields = None):
		""" 
		
		Args:
			| searchTuningRuleSortFieldsIn(searchTuningRuleSortFieldsIn) - 
			| responseFields (string) - 
		
		Returns:
			| SearchTuningRuleSortFields 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/catalog/admin/search/searchtuningrulesortfields?responseFields={responseFields}", "POST", UrlLocation.TenantPod, False);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).withBody(searchTuningRuleSortFieldsIn).execute();
		return self.client.result();

	
		
	def updateSynonymDefinitionCollection(self,collection, localeCode, responseFields = None):
		""" 
		
		Args:
			| collection(collection) - 
			| localeCode (string) - 
			| responseFields (string) - 
		
		Returns:
			| SynonymDefinitionCollection 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/catalog/admin/search/synonym-definitions/{localeCode}?responseFields={responseFields}", "POST", UrlLocation.TenantPod, False);
		url.formatUrl("localeCode", localeCode);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).withBody(collection).execute();
		return self.client.result();

	
		
	def addSynonymDefinition(self,synonymDefinition, responseFields = None):
		""" 
		
		Args:
			| synonymDefinition(synonymDefinition) - 
			| responseFields (string) - 
		
		Returns:
			| SynonymDefinition 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/catalog/admin/search/synonyms?responseFields={responseFields}", "POST", UrlLocation.TenantPod, False);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).withBody(synonymDefinition).execute();
		return self.client.result();

	
		
	def updateSearchTuningRule(self,searchTuningRuleIn, searchTuningRuleCode, responseFields = None):
		""" 
		
		Args:
			| searchTuningRuleIn(searchTuningRuleIn) - 
			| searchTuningRuleCode (string) - 
			| responseFields (string) - 
		
		Returns:
			| SearchTuningRule 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/catalog/admin/search/searchtuningrules/{searchTuningRuleCode}?responseFields={responseFields}", "PUT", UrlLocation.TenantPod, False);
		url.formatUrl("responseFields", responseFields);
		url.formatUrl("searchTuningRuleCode", searchTuningRuleCode);
		self.client.withResourceUrl(url).withBody(searchTuningRuleIn).execute();
		return self.client.result();

	
		
	def updateSettings(self,settings, responseFields = None):
		""" 
		
		Args:
			| settings(settings) - 
			| responseFields (string) - 
		
		Returns:
			| SearchSettings 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/catalog/admin/search/settings?responseFields={responseFields}", "PUT", UrlLocation.TenantPod, False);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).withBody(settings).execute();
		return self.client.result();

	
		
	def updateSynonymDefinition(self,synonymDefinition, synonymId, responseFields = None):
		""" 
		
		Args:
			| synonymDefinition(synonymDefinition) - 
			| synonymId (int) - 
			| responseFields (string) - 
		
		Returns:
			| SynonymDefinition 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/catalog/admin/search/synonyms/{synonymId}?responseFields={responseFields}", "PUT", UrlLocation.TenantPod, False);
		url.formatUrl("responseFields", responseFields);
		url.formatUrl("synonymId", synonymId);
		self.client.withResourceUrl(url).withBody(synonymDefinition).execute();
		return self.client.result();

	
		
	def deleteSearchTuningRule(self,searchTuningRuleCode):
		""" 
		
		Args:
			| searchTuningRuleCode (string) - 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/catalog/admin/search/searchtuningrules/{searchTuningRuleCode}", "DELETE", UrlLocation.TenantPod, False);
		url.formatUrl("searchTuningRuleCode", searchTuningRuleCode);
		self.client.withResourceUrl(url).execute();

	
		
	def deleteSynonymDefinition(self,synonymId):
		""" 
		
		Args:
			| synonymId (int) - 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/catalog/admin/search/synonyms/{synonymId}", "DELETE", UrlLocation.TenantPod, False);
		url.formatUrl("synonymId", synonymId);
		self.client.withResourceUrl(url).execute();

	
	
	