
"""
    This code was generated by Codezu.     

    Changes to this file may cause incorrect behavior and will be lost if
    the code is regenerated.
"""


from mozurestsdk.mozuclient import default as default_client
from mozurestsdk.mozuurl import MozuUrl;
from mozurestsdk.urllocation import UrlLocation
from mozurestsdk.apicontext import ApiContext;

class Shipment(object):
	def __init__(self, apiContext: ApiContext = None, mozuClient = None):
		self.client = mozuClient or default_client();
		if (apiContext is not None):
			self.client.withApiContext(apiContext);
		else:
			self.client.withApiContext(ApiContext());
	
	def getShipment(self,returnId, shipmentId, responseFields = None):
		""" 
		
		Args:
			| returnId (string) - Unique identifier of the return associated with the replacement shipment to retrieve.
			| shipmentId (string) - Unique identifier of the return replacement shipment to retrieve.
			| responseFields (string) - 
		
		Returns:
			| Shipment 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/returns/{returnId}/shipments/{shipmentId}?responseFields={responseFields}", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("responseFields", responseFields);
		url.formatUrl("returnId", returnId);
		url.formatUrl("shipmentId", shipmentId);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def createPackageShipments(self,packageIds, returnId):
		""" 
		
		Args:
			| packageIds(array|packageIds) - List of packages in the return replacement shipment.
			| returnId (string) - Unique identifier of the return for which to create replacement package shipments.
		
		Returns:
			| array of Package 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/returns/{returnId}/shipments", "POST", UrlLocation.TenantPod, False);
		url.formatUrl("returnId", returnId);
		self.client.withResourceUrl(url).withBody(packageIds).execute();
		return self.client.result();

	
		
	def deleteShipment(self,returnId, shipmentId):
		""" 
		
		Args:
			| returnId (string) - Unique identifier of the return associated with the replacement shipment to delete.
			| shipmentId (string) - Unique identifier of the return replacement shipment to delete.
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/returns/{returnId}/shipments/{shipmentId}", "DELETE", UrlLocation.TenantPod, False);
		url.formatUrl("returnId", returnId);
		url.formatUrl("shipmentId", shipmentId);
		self.client.withResourceUrl(url).execute();

	
	
	