
"""
    This code was generated by Codezu.     

    Changes to this file may cause incorrect behavior and will be lost if
    the code is regenerated.
"""


from mozurestsdk.mozuclient import default as default_client
from mozurestsdk.mozuurl import MozuUrl;
from mozurestsdk.urllocation import UrlLocation
from mozurestsdk.apicontext import ApiContext;

class Cart(object):
	def __init__(self, apiContext: ApiContext = None, mozuClient = None):
		self.client = mozuClient or default_client();
		if (apiContext is not None):
			self.client.withApiContext(apiContext);
		else:
			self.client.withApiContext(ApiContext());
	
	def getCart(self,cartId, responseFields = None):
		""" 
		
		Args:
			| cartId (string) - Identifier of the cart to retrieve.
			| responseFields (string) - 
		
		Returns:
			| Cart 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/carts/{cartId}?responseFields={responseFields}", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("cartId", cartId);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getOrCreateCart(self,responseFields = None):
		""" 
		
		Args:
			| responseFields (string) - 
		
		Returns:
			| Cart 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/carts/current?responseFields={responseFields}", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getCartSummary(self,responseFields = None):
		""" 
		
		Args:
			| responseFields (string) - 
		
		Returns:
			| CartSummary 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/carts/summary?responseFields={responseFields}", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getUserCartSummary(self,userId, responseFields = None):
		""" 
		
		Args:
			| userId (string) - Unique identifier of the user whose cart details you want to retrieve.
			| responseFields (string) - 
		
		Returns:
			| CartSummary 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/carts/user/{userId}/summary?responseFields={responseFields}", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("responseFields", responseFields);
		url.formatUrl("userId", userId);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getUserCart(self,userId, responseFields = None):
		""" 
		
		Args:
			| userId (string) - Unique identifier of the user whose cart you want to retrieve.
			| responseFields (string) - 
		
		Returns:
			| Cart 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/carts/user/{userId}?responseFields={responseFields}", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("responseFields", responseFields);
		url.formatUrl("userId", userId);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def updateCart(self,cart, responseFields = None):
		""" 
		
		Args:
			| cart(cart) - All of the properties of the cart to update. The product code is required.
			| responseFields (string) - 
		
		Returns:
			| Cart 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/carts/current?responseFields={responseFields}", "PUT", UrlLocation.TenantPod, False);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).withBody(cart).execute();
		return self.client.result();

	
		
	def deleteCart(self,cartId):
		""" 
		
		Args:
			| cartId (string) - Identifier of the cart to delete.
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/carts/{cartId}", "DELETE", UrlLocation.TenantPod, False);
		url.formatUrl("cartId", cartId);
		self.client.withResourceUrl(url).execute();

	
		
	def deleteCurrentCart(self,):
		""" 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/carts/current", "DELETE", UrlLocation.TenantPod, False);
		self.client.withResourceUrl(url).execute();

	
	
	