
"""
    This code was generated by Codezu.     

    Changes to this file may cause incorrect behavior and will be lost if
    the code is regenerated.
"""


from mozurestsdk.mozuclient import default as default_client
from mozurestsdk.mozuurl import MozuUrl;
from mozurestsdk.urllocation import UrlLocation
from mozurestsdk.apicontext import ApiContext;

class Checkout(object):
	def __init__(self, apiContext: ApiContext = None, mozuClient = None):
		self.client = mozuClient or default_client();
		if (apiContext is not None):
			self.client.withApiContext(apiContext);
		else:
			self.client.withApiContext(ApiContext());
	
	def getCheckouts(self,startIndex = None, pageSize = None, sortBy = None, filter = None, q = None, qLimit = None, responseFields = None):
		""" 
		
		Args:
			| startIndex (int) - 
			| pageSize (int) - 
			| sortBy (string) - 
			| filter (string) - 
			| q (string) - 
			| qLimit (int) - 
			| responseFields (string) - 
		
		Returns:
			| CheckoutCollection 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/checkouts/?startIndex={startIndex}&pageSize={pageSize}&sortBy={sortBy}&filter={filter}&q={q}&qLimit={qLimit}&responseFields={responseFields}", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("filter", filter);
		url.formatUrl("pageSize", pageSize);
		url.formatUrl("q", q);
		url.formatUrl("qLimit", qLimit);
		url.formatUrl("responseFields", responseFields);
		url.formatUrl("sortBy", sortBy);
		url.formatUrl("startIndex", startIndex);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getAvailableActions(self,checkoutId):
		""" 
		
		Args:
			| checkoutId (string) - 
		
		Returns:
			| array of string 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/checkouts/{checkoutId}/actions", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("checkoutId", checkoutId);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getAvailableShippingMethods(self,checkoutId):
		""" 
		
		Args:
			| checkoutId (string) - 
		
		Returns:
			| array of CheckoutGroupRates 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/checkouts/{checkoutId}/shippingMethods", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("checkoutId", checkoutId);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getCheckout(self,checkoutId, responseFields = None):
		""" 
		
		Args:
			| checkoutId (string) - 
			| responseFields (string) - 
		
		Returns:
			| Checkout 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/checkouts/{checkoutId}?responseFields={responseFields}", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("checkoutId", checkoutId);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def createCheckoutFromCart(self,cartId, responseFields = None):
		""" 
		
		Args:
			| cartId (string) - 
			| responseFields (string) - 
		
		Returns:
			| Checkout 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/checkouts/?cartId={cartId}&responseFields={responseFields}", "POST", UrlLocation.TenantPod, False);
		url.formatUrl("cartId", cartId);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def performCheckoutAction(self,action, checkoutId, responseFields = None):
		""" 
		
		Args:
			| action(action) - 
			| checkoutId (string) - 
			| responseFields (string) - 
		
		Returns:
			| Checkout 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/checkouts/{checkoutId}/actions?responseFields={responseFields}", "POST", UrlLocation.TenantPod, False);
		url.formatUrl("checkoutId", checkoutId);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).withBody(action).execute();
		return self.client.result();

	
		
	def resendCheckoutConfirmationEmail(self,checkoutId):
		""" 
		
		Args:
			| checkoutId (string) - 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/checkouts/{checkoutId}/email/resend", "POST", UrlLocation.TenantPod, False);
		url.formatUrl("checkoutId", checkoutId);
		self.client.withResourceUrl(url).execute();

	
		
	def setShippingMethods(self,groupShippingMethods, checkoutId, responseFields = None):
		""" 
		
		Args:
			| groupShippingMethods(array|groupShippingMethods) - 
			| checkoutId (string) - 
			| responseFields (string) - 
		
		Returns:
			| Checkout 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/checkouts/{checkoutId}/shippingMethods?responseFields={responseFields}", "POST", UrlLocation.TenantPod, False);
		url.formatUrl("checkoutId", checkoutId);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).withBody(groupShippingMethods).execute();
		return self.client.result();

	
		
	def updateCheckout(self,checkout, checkoutId, responseFields = None):
		""" 
		
		Args:
			| checkout(checkout) - 
			| checkoutId (string) - 
			| responseFields (string) - 
		
		Returns:
			| Checkout 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/checkouts/{checkoutId}?responseFields={responseFields}", "POST", UrlLocation.TenantPod, False);
		url.formatUrl("checkoutId", checkoutId);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).withBody(checkout).execute();
		return self.client.result();

	
		
	def processDigitalWallet(self,digitalWallet, checkoutId, digitalWalletType, responseFields = None):
		""" 
		
		Args:
			| digitalWallet(digitalWallet) - 
			| checkoutId (string) - 
			| digitalWalletType (string) - 
			| responseFields (string) - 
		
		Returns:
			| Checkout 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/checkouts/{checkoutId}/digitalWallet/{digitalWalletType}?responseFields={responseFields}", "PUT", UrlLocation.TenantPod, False);
		url.formatUrl("checkoutId", checkoutId);
		url.formatUrl("digitalWalletType", digitalWalletType);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).withBody(digitalWallet).execute();
		return self.client.result();

	
		
	def changeCheckoutPriceList(self,priceListCode, checkoutId, responseFields = None):
		""" 
		
		Args:
			| priceListCode(priceListCode) - 
			| checkoutId (string) - 
			| responseFields (string) - 
		
		Returns:
			| Checkout 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/checkouts/{checkoutId}/priceList?responseFields={responseFields}", "PUT", UrlLocation.TenantPod, False);
		url.formatUrl("checkoutId", checkoutId);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).withBody(priceListCode).execute();
		return self.client.result();

	
	
	