
"""
    This code was generated by Codezu.     

    Changes to this file may cause incorrect behavior and will be lost if
    the code is regenerated.
"""


from mozurestsdk.mozuclient import default as default_client
from mozurestsdk.mozuurl import MozuUrl;
from mozurestsdk.urllocation import UrlLocation
from mozurestsdk.apicontext import ApiContext;

class Order(object):
	def __init__(self, apiContext: ApiContext = None, mozuClient = None):
		self.client = mozuClient or default_client();
		if (apiContext is not None):
			self.client.withApiContext(apiContext);
		else:
			self.client.withApiContext(ApiContext());
	
	def getOrders(self,startIndex = None, pageSize = None, sortBy = None, filter = None, q = None, qLimit = None, includeBin = False, responseFields = None):
		""" 
		
		Args:
			| startIndex (int) - 
			| pageSize (int) - Used to page results from a query. Indicates the maximum number of entities to return from a query. Default value: 20. Max value: 200.
			| sortBy (string) - The element to sort the results by and the order in which the results appear. Either ascending order (a-z) which accepts 'asc' or 'asc' or descending order (z-a) which accepts 'desc' or 'desc'. The sortBy parameter follows an available property. For examp
			| filter (string) - A set of expressions that consist of a field, operator, and value and represent search parameter syntax when filtering results of a query. You can filter an order's search results by any of its properties, including status, contact information, or total. Valid operators include equals (eq), does not equal (ne), greater than (gt), less than (lt), greater than or equal to (ge), less than or equal to (le), starts with (sw), or contains (cont). For example - "filter=Status+eq+Submitted"
			| q (string) - A list of order search terms to use in the query when searching across order number and the name or email of the billing contact. Separate multiple search terms with a space character.
			| qLimit (int) - The maximum number of search results to return in the response. You can limit any range between 1-100.
			| includeBin (bool) - 
			| responseFields (string) - 
		
		Returns:
			| OrderCollection 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/orders/?startIndex={startIndex}&pageSize={pageSize}&sortBy={sortBy}&filter={filter}&q={q}&qLimit={qLimit}&includeBin={includeBin}&responseFields={responseFields}", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("filter", filter);
		url.formatUrl("includeBin", includeBin);
		url.formatUrl("pageSize", pageSize);
		url.formatUrl("q", q);
		url.formatUrl("qLimit", qLimit);
		url.formatUrl("responseFields", responseFields);
		url.formatUrl("sortBy", sortBy);
		url.formatUrl("startIndex", startIndex);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getAvailableActions(self,orderId):
		""" 
		
		Args:
			| orderId (string) - Unique identifier of the available order actions to get.
		
		Returns:
			| array of string 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/orders/{orderId}/actions", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("orderId", orderId);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getTaxableOrders(self,orderId):
		""" 
		
		Args:
			| orderId (string) - Unique identifier of the order to retrieve.
		
		Returns:
			| array of TaxableOrder 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/orders/{orderId}/taxableorders", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("orderId", orderId);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getOrder(self,orderId, draft = False, includeBin = False, responseFields = None):
		""" 
		
		Args:
			| orderId (string) - Unique identifier of the order details to get.
			| draft (bool) - If true, retrieve the draft version of the order, which might include uncommitted changes to the order or its components.
			| includeBin (bool) - 
			| responseFields (string) - 
		
		Returns:
			| Order 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/orders/{orderId}?draft={draft}&includeBin={includeBin}&responseFields={responseFields}", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("draft", draft);
		url.formatUrl("includeBin", includeBin);
		url.formatUrl("orderId", orderId);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def createOrderFromCart(self,cartId, responseFields = None):
		""" 
		
		Args:
			| cartId (string) - Unique identifier of the cart. This is the original cart ID expressed as a GUID.
			| responseFields (string) - 
		
		Returns:
			| Order 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/orders/?cartId={cartId}&responseFields={responseFields}", "POST", UrlLocation.TenantPod, False);
		url.formatUrl("cartId", cartId);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def createOrder(self,order, responseFields = None):
		""" 
		
		Args:
			| order(order) - Properties of the order to create and submit.
			| responseFields (string) - 
		
		Returns:
			| Order 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/orders/?responseFields={responseFields}", "POST", UrlLocation.TenantPod, False);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).withBody(order).execute();
		return self.client.result();

	
		
	def performOrderAction(self,action, orderId, responseFields = None):
		""" 
		
		Args:
			| action(action) - The action to perform for the order.
			| orderId (string) - Unique identifier of the order.
			| responseFields (string) - 
		
		Returns:
			| Order 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/orders/{orderId}/actions?responseFields={responseFields}", "POST", UrlLocation.TenantPod, False);
		url.formatUrl("orderId", orderId);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).withBody(action).execute();
		return self.client.result();

	
		
	def priceOrder(self,order, refreshShipping, couponCodeToApply = None, responseFields = None):
		""" 
		
		Args:
			| order(order) - 
			| refreshShipping (bool) - 
			| couponCodeToApply (string) - 
			| responseFields (string) - 
		
		Returns:
			| Order 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/orders/price?refreshShipping={refreshShipping}&couponCodeToApply={couponCodeToApply}&responseFields={responseFields}", "POST", UrlLocation.TenantPod, False);
		url.formatUrl("couponCodeToApply", couponCodeToApply);
		url.formatUrl("refreshShipping", refreshShipping);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).withBody(order).execute();
		return self.client.result();

	
		
	def processDigitalWallet(self,digitalWallet, orderId, digitalWalletType, responseFields = None):
		""" 
		
		Args:
			| digitalWallet(digitalWallet) - 
			| orderId (string) - 
			| digitalWalletType (string) - 
			| responseFields (string) - 
		
		Returns:
			| Order 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/orders/{orderId}/digitalWallet/{digitalWalletType}?responseFields={responseFields}", "PUT", UrlLocation.TenantPod, False);
		url.formatUrl("digitalWalletType", digitalWalletType);
		url.formatUrl("orderId", orderId);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).withBody(digitalWallet).execute();
		return self.client.result();

	
		
	def updateOrderDiscount(self,discount, orderId, discountId, updateMode = None, version = None, responseFields = None):
		""" 
		
		Args:
			| discount(discount) - Properties of the order discount to update.
			| orderId (string) - Unique identifier of the order discount. System-supplied and read only.
			| discountId (int) - Unique identifier of the discount. System-supplied and read only.
			| updateMode (string) - Specifies whether to modify the discount by updating the original order, updating the order in draft mode, or updating the order in draft mode and then committing the changes to the original. Draft mode enables users to make incremental order changes before committing the changes to the original order. Valid values are "ApplyToOriginal," "ApplyToDraft," or "ApplyAndCommit."
			| version (string) - 
			| responseFields (string) - 
		
		Returns:
			| Order 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/orders/{orderId}/discounts/{discountId}?updatemode={updateMode}&version={version}&responseFields={responseFields}", "PUT", UrlLocation.TenantPod, False);
		url.formatUrl("discountId", discountId);
		url.formatUrl("orderId", orderId);
		url.formatUrl("responseFields", responseFields);
		url.formatUrl("updateMode", updateMode);
		url.formatUrl("version", version);
		self.client.withResourceUrl(url).withBody(discount).execute();
		return self.client.result();

	
		
	def deleteOrderDraft(self,orderId, version = None):
		""" 
		
		Args:
			| orderId (string) - Unique identifier of the order associated with the draft to delete.
			| version (string) - If applicable, the version of the order draft to delete.
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/orders/{orderId}/draft?version={version}", "PUT", UrlLocation.TenantPod, False);
		url.formatUrl("orderId", orderId);
		url.formatUrl("version", version);
		self.client.withResourceUrl(url).execute();

	
		
	def resendOrderConfirmationEmail(self,action, orderId):
		""" 
		
		Args:
			| action(action) - 
			| orderId (string) - 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/orders/{orderId}/email/resend", "PUT", UrlLocation.TenantPod, False);
		url.formatUrl("orderId", orderId);
		self.client.withResourceUrl(url).withBody(action).execute();

	
		
	def changeOrderPriceList(self,priceListCode, orderId, updateMode = None, version = None, responseFields = None):
		""" 
		
		Args:
			| priceListCode(priceListCode) - 
			| orderId (string) - 
			| updateMode (string) - 
			| version (string) - 
			| responseFields (string) - 
		
		Returns:
			| Order 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/orders/{orderId}/priceList?updatemode={updateMode}&version={version}&responseFields={responseFields}", "PUT", UrlLocation.TenantPod, False);
		url.formatUrl("orderId", orderId);
		url.formatUrl("responseFields", responseFields);
		url.formatUrl("updateMode", updateMode);
		url.formatUrl("version", version);
		self.client.withResourceUrl(url).withBody(priceListCode).execute();
		return self.client.result();

	
		
	def changeOrderUserId(self,orderId, responseFields = None):
		""" 
		
		Args:
			| orderId (string) - Unique identifier of the order.
			| responseFields (string) - 
		
		Returns:
			| Order 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/orders/{orderId}/users?responseFields={responseFields}", "PUT", UrlLocation.TenantPod, False);
		url.formatUrl("orderId", orderId);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def updateOrder(self,order, orderId, updateMode = None, version = None, responseFields = None):
		""" 
		
		Args:
			| order(order) - The properties of the order to update.
			| orderId (string) - Unique identifier of the order to update.
			| updateMode (string) - Specifies whether to update the original order, update the order in draft mode, or update the order in draft mode and then commit the changes to the original. Draft mode enables users to make incremental order changes before committing the changes to the original order. Valid values are "ApplyToOriginal," "ApplyToDraft," or "ApplyAndCommit."
			| version (string) - 
			| responseFields (string) - 
		
		Returns:
			| Order 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/orders/{orderId}?updatemode={updateMode}&version={version}&responseFields={responseFields}", "PUT", UrlLocation.TenantPod, False);
		url.formatUrl("orderId", orderId);
		url.formatUrl("responseFields", responseFields);
		url.formatUrl("updateMode", updateMode);
		url.formatUrl("version", version);
		self.client.withResourceUrl(url).withBody(order).execute();
		return self.client.result();

	
	
	