
"""
    This code was generated by Codezu.     

    Changes to this file may cause incorrect behavior and will be lost if
    the code is regenerated.
"""


from mozurestsdk.mozuclient import default as default_client
from mozurestsdk.mozuurl import MozuUrl;
from mozurestsdk.urllocation import UrlLocation
from mozurestsdk.apicontext import ApiContext;

class Return(object):
	def __init__(self, apiContext: ApiContext = None, mozuClient = None):
		self.client = mozuClient or default_client();
		if (apiContext is not None):
			self.client.withApiContext(apiContext);
		else:
			self.client.withApiContext(ApiContext());
	
	def getReturns(self,startIndex = None, pageSize = None, sortBy = None, filter = None, q = None, responseFields = None):
		""" 
		
		Args:
			| startIndex (int) - 
			| pageSize (int) - 
			| sortBy (string) - 
			| filter (string) - 
			| q (string) - 
			| responseFields (string) - 
		
		Returns:
			| ReturnCollection 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/returns/?startIndex={startIndex}&pageSize={pageSize}&sortBy={sortBy}&filter={filter}&q={q}&responseFields={responseFields}", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("filter", filter);
		url.formatUrl("pageSize", pageSize);
		url.formatUrl("q", q);
		url.formatUrl("responseFields", responseFields);
		url.formatUrl("sortBy", sortBy);
		url.formatUrl("startIndex", startIndex);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getAvailableReturnActions(self,returnId):
		""" 
		
		Args:
			| returnId (string) - Unique identifier of the return for which to retrieve available actions.
		
		Returns:
			| array of string 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/returns/{returnId}/actions", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("returnId", returnId);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getReturnItem(self,returnId, returnItemId, responseFields = None):
		""" 
		
		Args:
			| returnId (string) - 
			| returnItemId (string) - 
			| responseFields (string) - 
		
		Returns:
			| ReturnItem 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/returns/{returnId}/items/{returnItemId}?responseFields={responseFields}", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("responseFields", responseFields);
		url.formatUrl("returnId", returnId);
		url.formatUrl("returnItemId", returnItemId);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getReturnItems(self,returnId, responseFields = None):
		""" 
		
		Args:
			| returnId (string) - 
			| responseFields (string) - 
		
		Returns:
			| ReturnItemCollection 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/returns/{returnId}/items?responseFields={responseFields}", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("responseFields", responseFields);
		url.formatUrl("returnId", returnId);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getAvailablePaymentActionsForReturn(self,returnId, paymentId):
		""" 
		
		Args:
			| returnId (string) - Unique identifier of the return associated with the payment.
			| paymentId (string) - Unique identifier of the payment for which to perform the action.
		
		Returns:
			| array of string 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/returns/{returnId}/payments/{paymentId}/actions", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("paymentId", paymentId);
		url.formatUrl("returnId", returnId);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getPayment(self,returnId, paymentId, responseFields = None):
		""" 
		
		Args:
			| returnId (string) - Unique identifier of the return associated with the payment.
			| paymentId (string) - Unique identifier of the return payment to retrieve.
			| responseFields (string) - 
		
		Returns:
			| Payment 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/returns/{returnId}/payments/{paymentId}?responseFields={responseFields}", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("paymentId", paymentId);
		url.formatUrl("responseFields", responseFields);
		url.formatUrl("returnId", returnId);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getPayments(self,returnId, responseFields = None):
		""" 
		
		Args:
			| returnId (string) - Returns the details of the refund payment associated with the return specified in the request.
			| responseFields (string) - 
		
		Returns:
			| PaymentCollection 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/returns/{returnId}/payments?responseFields={responseFields}", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("responseFields", responseFields);
		url.formatUrl("returnId", returnId);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getReturn(self,returnId, responseFields = None):
		""" 
		
		Args:
			| returnId (string) - Returns the properties of the return specified in the request as well as system-supplied information.
			| responseFields (string) - 
		
		Returns:
			| Return 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/returns/{returnId}?responseFields={responseFields}", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("responseFields", responseFields);
		url.formatUrl("returnId", returnId);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getReasons(self,responseFields = None):
		""" 
		
		Args:
			| responseFields (string) - 
		
		Returns:
			| ReasonCollection 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/returns/reasons?responseFields={responseFields}", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def createReturn(self,ret, responseFields = None):
		""" 
		
		Args:
			| ret(ret) - Wrapper for the properties of the return to create.
			| responseFields (string) - 
		
		Returns:
			| Return 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/returns/?responseFields={responseFields}", "POST", UrlLocation.TenantPod, False);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).withBody(ret).execute();
		return self.client.result();

	
		
	def createReturnItem(self,returnItem, returnId, responseFields = None):
		""" 
		
		Args:
			| returnItem(returnItem) - 
			| returnId (string) - 
			| responseFields (string) - 
		
		Returns:
			| Return 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/returns/{returnId}/items?responseFields={responseFields}", "POST", UrlLocation.TenantPod, False);
		url.formatUrl("responseFields", responseFields);
		url.formatUrl("returnId", returnId);
		self.client.withResourceUrl(url).withBody(returnItem).execute();
		return self.client.result();

	
		
	def performPaymentActionForReturn(self,action, returnId, paymentId, responseFields = None):
		""" 
		
		Args:
			| action(action) - The payment action to perform for the refund payment.
			| returnId (string) - Unique identifier of the return associated with the refund payment.
			| paymentId (string) - Unique identifier of the return payment to update.
			| responseFields (string) - 
		
		Returns:
			| Return 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/returns/{returnId}/payments/{paymentId}/actions?responseFields={responseFields}", "POST", UrlLocation.TenantPod, False);
		url.formatUrl("paymentId", paymentId);
		url.formatUrl("responseFields", responseFields);
		url.formatUrl("returnId", returnId);
		self.client.withResourceUrl(url).withBody(action).execute();
		return self.client.result();

	
		
	def createPaymentActionForReturn(self,action, returnId, responseFields = None):
		""" 
		
		Args:
			| action(action) - The payment action to perform for the customer return.
			| returnId (string) - Unique identifier of the return associated with the payment action.
			| responseFields (string) - 
		
		Returns:
			| Return 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/returns/{returnId}/payments/actions?responseFields={responseFields}", "POST", UrlLocation.TenantPod, False);
		url.formatUrl("responseFields", responseFields);
		url.formatUrl("returnId", returnId);
		self.client.withResourceUrl(url).withBody(action).execute();
		return self.client.result();

	
		
	def createReturnShippingOrder(self,itemQuantities, returnId, responseFields = None):
		""" 
		
		Args:
			| itemQuantities(array|itemQuantities) - 
			| returnId (string) - 
			| responseFields (string) - 
		
		Returns:
			| Order 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/returns/{returnId}/ship?responseFields={responseFields}", "POST", UrlLocation.TenantPod, False);
		url.formatUrl("responseFields", responseFields);
		url.formatUrl("returnId", returnId);
		self.client.withResourceUrl(url).withBody(itemQuantities).execute();
		return self.client.result();

	
		
	def performReturnActions(self,action, responseFields = None):
		""" 
		
		Args:
			| action(action) - The name of the return action to perform, such as "Reject" or "Authorize".
			| responseFields (string) - 
		
		Returns:
			| ReturnCollection 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/returns/actions?responseFields={responseFields}", "POST", UrlLocation.TenantPod, False);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).withBody(action).execute();
		return self.client.result();

	
		
	def updateReturn(self,ret, returnId, responseFields = None):
		""" 
		
		Args:
			| ret(ret) - Wrapper for the array of properties to update for the return.
			| returnId (string) - Unique identifier of the return.
			| responseFields (string) - 
		
		Returns:
			| Return 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/returns/{returnId}?responseFields={responseFields}", "PUT", UrlLocation.TenantPod, False);
		url.formatUrl("responseFields", responseFields);
		url.formatUrl("returnId", returnId);
		self.client.withResourceUrl(url).withBody(ret).execute();
		return self.client.result();

	
		
	def resendReturnEmail(self,action):
		""" 
		
		Args:
			| action(action) - 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/returns/email/resend", "PUT", UrlLocation.TenantPod, False);
		self.client.withResourceUrl(url).withBody(action).execute();

	
		
	def deleteOrderItem(self,returnId, returnItemId):
		""" 
		
		Args:
			| returnId (string) - 
			| returnItemId (string) - 
		
		Returns:
			| Return 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/returns/{orderId}/items/{orderItemId}?updatemode={updateMode}&version={version}", "DELETE", UrlLocation.TenantPod, False);
		url.formatUrl("returnId", returnId);
		url.formatUrl("returnItemId", returnItemId);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def deleteReturn(self,returnId):
		""" 
		
		Args:
			| returnId (string) - Unique identifier of the return to delete.
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/returns/{returnId}", "DELETE", UrlLocation.TenantPod, False);
		url.formatUrl("returnId", returnId);
		self.client.withResourceUrl(url).execute();

	
	
	