
"""
    This code was generated by Codezu.     

    Changes to this file may cause incorrect behavior and will be lost if
    the code is regenerated.
"""


from mozurestsdk.mozuclient import default as default_client
from mozurestsdk.mozuurl import MozuUrl;
from mozurestsdk.urllocation import UrlLocation
from mozurestsdk.apicontext import ApiContext;

class TargetRule(object):
	def __init__(self, apiContext: ApiContext = None, mozuClient = None):
		self.client = mozuClient or default_client();
		if (apiContext is not None):
			self.client.withApiContext(apiContext);
		else:
			self.client.withApiContext(ApiContext());
	
	def getTargetRules(self,startIndex = None, pageSize = None, sortBy = None, filter = None, responseFields = None):
		""" 
		
		Args:
			| startIndex (int) - 
			| pageSize (int) - 
			| sortBy (string) - 
			| filter (string) - 
			| responseFields (string) - 
		
		Returns:
			| TargetRuleCollection 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/targetrules/?startIndex={startIndex}&pageSize={pageSize}&sortBy={sortBy}&filter={filter}&responseFields={responseFields}", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("filter", filter);
		url.formatUrl("pageSize", pageSize);
		url.formatUrl("responseFields", responseFields);
		url.formatUrl("sortBy", sortBy);
		url.formatUrl("startIndex", startIndex);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getTargetRule(self,code, responseFields = None):
		""" 
		
		Args:
			| code (string) - 
			| responseFields (string) - 
		
		Returns:
			| TargetRule 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/targetrules/{code}?responseFields={responseFields}", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("code", code);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def createTargetRule(self,targetRule, responseFields = None):
		""" 
		
		Args:
			| targetRule(targetRule) - 
			| responseFields (string) - 
		
		Returns:
			| TargetRule 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/targetrules/?responseFields={responseFields}", "POST", UrlLocation.TenantPod, False);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).withBody(targetRule).execute();
		return self.client.result();

	
		
	def validateTargetRule(self,targetRule):
		""" 
		
		Args:
			| targetRule(targetRule) - 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/targetrules/validate", "POST", UrlLocation.TenantPod, False);
		self.client.withResourceUrl(url).withBody(targetRule).execute();

	
		
	def updateTargetRule(self,targetRule, code, responseFields = None):
		""" 
		
		Args:
			| targetRule(targetRule) - 
			| code (string) - 
			| responseFields (string) - 
		
		Returns:
			| TargetRule 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/targetrules/{code}?responseFields={responseFields}", "PUT", UrlLocation.TenantPod, False);
		url.formatUrl("code", code);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).withBody(targetRule).execute();
		return self.client.result();

	
		
	def deleteTargetRule(self,code):
		""" 
		
		Args:
			| code (string) - 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/targetrules/{code}", "DELETE", UrlLocation.TenantPod, False);
		url.formatUrl("code", code);
		self.client.withResourceUrl(url).execute();

	
	
	