
"""
    This code was generated by Codezu.     

    Changes to this file may cause incorrect behavior and will be lost if
    the code is regenerated.
"""


from mozurestsdk.mozuclient import default as default_client
from mozurestsdk.mozuurl import MozuUrl;
from mozurestsdk.urllocation import UrlLocation
from mozurestsdk.apicontext import ApiContext;

class Wishlist(object):
	def __init__(self, apiContext: ApiContext = None, mozuClient = None):
		self.client = mozuClient or default_client();
		if (apiContext is not None):
			self.client.withApiContext(apiContext);
		else:
			self.client.withApiContext(ApiContext());
	
	def getWishlists(self,startIndex = None, pageSize = None, sortBy = None, filter = None, q = None, qLimit = None, responseFields = None):
		""" 
		
		Args:
			| startIndex (int) - When creating paged results from a query, this value indicates the zero-based offset in the complete result set where the returned entities begin. For example, with pageSize set to 25, to get the 51st through the 75th items, set this parameter to 50.
			| pageSize (int) - When creating paged results from a query, this value indicates the zero-based offset in the complete result set where the returned entities begin. For example, with this parameter set to 25, to get the 51st through the 75th items, set startIndex to 50.
			| sortBy (string) - The element to sort the results by and the channel in which the results appear. Either ascending (a-z) or descending (z-a) channel. Optional. Refer to [Sorting and Filtering](../../../../Developer/api-guides/sorting-filtering.htm) for more information.
			| filter (string) - A set of filter expressions representing the search parameters for a query. This parameter is optional. Refer to [Sorting and Filtering](../../../../Developer/api-guides/sorting-filtering.htm) for a list of supported filters.
			| q (string) - A list of order search terms (not phrases) to use in the query when searching across order number and the name or email of the billing contact. When entering, separate multiple search terms with a space character.
			| qLimit (int) - The maximum number of search results to return in the response. You can limit any range between 1-100.
			| responseFields (string) - Filtering syntax appended to an API call to increase or decrease the amount of data returned inside a JSON object. This parameter should only be used to retrieve data. Attempting to update data using this parameter may cause data loss.
		
		Returns:
			| WishlistCollection 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/wishlists/?startIndex={startIndex}&pageSize={pageSize}&sortBy={sortBy}&filter={filter}&q={q}&qLimit={qLimit}&responseFields={responseFields}", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("filter", filter);
		url.formatUrl("pageSize", pageSize);
		url.formatUrl("q", q);
		url.formatUrl("qLimit", qLimit);
		url.formatUrl("responseFields", responseFields);
		url.formatUrl("sortBy", sortBy);
		url.formatUrl("startIndex", startIndex);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getWishlist(self,wishlistId, responseFields = None):
		""" 
		
		Args:
			| wishlistId (string) - Unique identifier of the wish list.
			| responseFields (string) - Filtering syntax appended to an API call to increase or decrease the amount of data returned inside a JSON object. This parameter should only be used to retrieve data. Attempting to update data using this parameter may cause data loss.
		
		Returns:
			| Wishlist 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/wishlists/{wishlistId}?responseFields={responseFields}", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("responseFields", responseFields);
		url.formatUrl("wishlistId", wishlistId);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getWishlistByName(self,customerAccountId, wishlistName, responseFields = None):
		""" 
		
		Args:
			| customerAccountId (int) - The unique identifier of the customer account for which to retrieve wish lists.
			| wishlistName (string) - The name of the wish list to retrieve.
			| responseFields (string) - Filtering syntax appended to an API call to increase or decrease the amount of data returned inside a JSON object. This parameter should only be used to retrieve data. Attempting to update data using this parameter may cause data loss.
		
		Returns:
			| Wishlist 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/wishlists/customers/{customerAccountId}/{wishlistName}?responseFields={responseFields}", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("customerAccountId", customerAccountId);
		url.formatUrl("responseFields", responseFields);
		url.formatUrl("wishlistName", wishlistName);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def createWishlist(self,wishlist, responseFields = None):
		""" 
		
		Args:
			| wishlist(wishlist) - Properties of a shopper wish list defined for a site, associated with a customer account.
			| responseFields (string) - Filtering syntax appended to an API call to increase or decrease the amount of data returned inside a JSON object. This parameter should only be used to retrieve data. Attempting to update data using this parameter may cause data loss.
		
		Returns:
			| Wishlist 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/wishlists/?responseFields={responseFields}", "POST", UrlLocation.TenantPod, False);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).withBody(wishlist).execute();
		return self.client.result();

	
		
	def updateWishlist(self,wishlist, wishlistId, responseFields = None):
		""" 
		
		Args:
			| wishlist(wishlist) - Properties of a shopper wish list defined for a site, associated with a customer account.
			| wishlistId (string) - Unique identifier of the wish list.
			| responseFields (string) - Filtering syntax appended to an API call to increase or decrease the amount of data returned inside a JSON object. This parameter should only be used to retrieve data. Attempting to update data using this parameter may cause data loss.
		
		Returns:
			| Wishlist 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/wishlists/{wishlistId}?responseFields={responseFields}", "PUT", UrlLocation.TenantPod, False);
		url.formatUrl("responseFields", responseFields);
		url.formatUrl("wishlistId", wishlistId);
		self.client.withResourceUrl(url).withBody(wishlist).execute();
		return self.client.result();

	
		
	def deleteWishlist(self,wishlistId):
		""" 
		
		Args:
			| wishlistId (string) - Unique identifier of the wish list.
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/wishlists/{wishlistId}", "DELETE", UrlLocation.TenantPod, False);
		url.formatUrl("wishlistId", wishlistId);
		self.client.withResourceUrl(url).execute();

	
	
	