
"""
    This code was generated by Codezu.     

    Changes to this file may cause incorrect behavior and will be lost if
    the code is regenerated.
"""


from mozurestsdk.mozuclient import default as default_client
from mozurestsdk.mozuurl import MozuUrl;
from mozurestsdk.urllocation import UrlLocation
from mozurestsdk.apicontext import ApiContext;

class TaxableTerritory(object):
	def __init__(self, apiContext: ApiContext = None, mozuClient = None):
		self.client = mozuClient or default_client();
		if (apiContext is not None):
			self.client.withApiContext(apiContext);
		else:
			self.client.withApiContext(ApiContext());
	
	def getTaxableTerritories(self,):
		""" 
		
		Returns:
			| array of TaxableTerritory 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/settings/general/taxableterritories", "GET", UrlLocation.TenantPod, False);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def addTaxableTerritory(self,taxableTerritory, responseFields = None):
		""" 
		
		Args:
			| taxableTerritory(taxableTerritory) - Properties of the taxable territory to create.
			| responseFields (string) - 
		
		Returns:
			| TaxableTerritory 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/settings/general/taxableterritories?responseFields={responseFields}", "POST", UrlLocation.TenantPod, False);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).withBody(taxableTerritory).execute();
		return self.client.result();

	
		
	def updateTaxableTerritories(self,taxableterritories):
		""" 
		
		Args:
			| taxableterritories(array|taxableterritories) - Properties of the taxable territories to update.
		
		Returns:
			| array of TaxableTerritory 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/settings/general/taxableterritories", "PUT", UrlLocation.TenantPod, False);
		self.client.withResourceUrl(url).withBody(taxableterritories).execute();
		return self.client.result();

	
	
	