
"""
    This code was generated by Codezu.     

    Changes to this file may cause incorrect behavior and will be lost if
    the code is regenerated.
"""


from mozurestsdk.mozuclient import default as default_client
from mozurestsdk.mozuurl import MozuUrl;
from mozurestsdk.urllocation import UrlLocation
from mozurestsdk.apicontext import ApiContext;

class Shipping(object):
	def __init__(self, apiContext: ApiContext = None, mozuClient = None):
		self.client = mozuClient or default_client();
		if (apiContext is not None):
			self.client.withApiContext(apiContext);
		else:
			self.client.withApiContext(ApiContext());
	
	def getMultiRates(self,rateRequestGroupList, includeRawResponse = False):
		""" 
		
		Args:
			| rateRequestGroupList(array|rateRequestGroupList) - The shipping rates available for the grouping.
			| includeRawResponse (bool) - Set this parameter to  to retrieve the full raw JSON response from a shipping carrier (instead of just the shipping rate).
		
		Returns:
			| array of RatesResponseGroup 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/catalog/storefront/shipping/request-multi-rates", "POST", UrlLocation.TenantPod, False);
		url.formatUrl("includeRawResponse", includeRawResponse);
		self.client.withResourceUrl(url).withBody(rateRequestGroupList).execute();
		return self.client.result();

	
		
	def getRates(self,rateRequest, includeRawResponse = False, responseFields = None):
		""" 
		
		Args:
			| rateRequest(rateRequest) - Properties required to request a shipping rate calculation.
			| includeRawResponse (bool) - Set this parameter to  to retrieve the full raw JSON response from a shipping carrier (instead of just the shipping rate).
			| responseFields (string) - Filtering syntax appended to an API call to increase or decrease the amount of data returned inside a JSON object. This parameter should only be used to retrieve data. Attempting to update data using this parameter may cause data loss.
		
		Returns:
			| RatesResponse 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/catalog/storefront/shipping/request-rates?responseFields={responseFields}", "POST", UrlLocation.TenantPod, False);
		url.formatUrl("includeRawResponse", includeRawResponse);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).withBody(rateRequest).execute();
		return self.client.result();

	
	
	