
"""
    This code was generated by Codezu.     

    Changes to this file may cause incorrect behavior and will be lost if
    the code is regenerated.
"""


from mozurestsdk.mozuclient import default as default_client
from mozurestsdk.mozuurl import MozuUrl;
from mozurestsdk.urllocation import UrlLocation
from mozurestsdk.apicontext import ApiContext;

class ProductVariation(object):
	def __init__(self, apiContext: ApiContext = None, dataViewMode="Live", mozuClient = None):
		if (apiContext is not None and apiContext.dataViewMode is None):
			apiContext.dataViewMode = dataViewMode;
		else:
			apiContext = ApiContext(dataViewMode = dataViewMode);
		self.client = mozuClient or default_client();
		self.client.withApiContext(apiContext);
	
	def getProductVariationLocalizedDeltaPrices(self,productCode, variationKey):
		""" 
		
		Args:
			| productCode (string) - 
			| variationKey (string) - 
		
		Returns:
			| array of ProductVariationDeltaPrice 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/catalog/admin/products/{productCode}/variations/{variationKey}/localizedDeltaPrice", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("productCode", productCode);
		url.formatUrl("variationKey", variationKey);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getProductVariationLocalizedDeltaPrice(self,productCode, variationKey, currencyCode, responseFields = None):
		""" 
		
		Args:
			| productCode (string) - 
			| variationKey (string) - 
			| currencyCode (string) - 
			| responseFields (string) - 
		
		Returns:
			| ProductVariationDeltaPrice 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/catalog/admin/products/{productCode}/variations/{variationKey}/localizedDeltaPrice/{currencyCode}?responseFields={responseFields}", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("currencyCode", currencyCode);
		url.formatUrl("productCode", productCode);
		url.formatUrl("responseFields", responseFields);
		url.formatUrl("variationKey", variationKey);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getProductVariationLocalizedPrices(self,productCode, variationKey):
		""" 
		
		Args:
			| productCode (string) - 
			| variationKey (string) - 
		
		Returns:
			| array of ProductVariationFixedPrice 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/catalog/admin/products/{productCode}/variations/{variationKey}/localizedPrice", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("productCode", productCode);
		url.formatUrl("variationKey", variationKey);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getProductVariationLocalizedPrice(self,productCode, variationKey, currencyCode, responseFields = None):
		""" 
		
		Args:
			| productCode (string) - 
			| variationKey (string) - 
			| currencyCode (string) - 
			| responseFields (string) - 
		
		Returns:
			| ProductVariationFixedPrice 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/catalog/admin/products/{productCode}/variations/{variationKey}/localizedPrice/{currencyCode}?responseFields={responseFields}", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("currencyCode", currencyCode);
		url.formatUrl("productCode", productCode);
		url.formatUrl("responseFields", responseFields);
		url.formatUrl("variationKey", variationKey);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getProductVariation(self,productCode, variationKey, responseFields = None):
		""" 
		
		Args:
			| productCode (string) - 
			| variationKey (string) - System-generated key that represents the attribute values that uniquely identify a specific product variation.
			| responseFields (string) - 
		
		Returns:
			| ProductVariation 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/catalog/admin/products/{productCode}/variations/{variationKey}?responseFields={responseFields}", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("productCode", productCode);
		url.formatUrl("responseFields", responseFields);
		url.formatUrl("variationKey", variationKey);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getProductVariations(self,productCode, startIndex = None, pageSize = None, sortBy = None, filter = None, responseFields = None):
		""" 
		
		Args:
			| productCode (string) - 
			| startIndex (int) - 
			| pageSize (int) - 
			| sortBy (string) - 
			| filter (string) - 
			| responseFields (string) - 
		
		Returns:
			| ProductVariationPagedCollection 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/catalog/admin/products/{productCode}/variations?startIndex={startIndex}&pageSize={pageSize}&sortBy={sortBy}&filter={filter}&responseFields={responseFields}", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("filter", filter);
		url.formatUrl("pageSize", pageSize);
		url.formatUrl("productCode", productCode);
		url.formatUrl("responseFields", responseFields);
		url.formatUrl("sortBy", sortBy);
		url.formatUrl("startIndex", startIndex);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def addProductVariationLocalizedDeltaPrice(self,localizedDeltaPrice, productCode, variationKey, responseFields = None):
		""" 
		
		Args:
			| localizedDeltaPrice(localizedDeltaPrice) - 
			| productCode (string) - 
			| variationKey (string) - 
			| responseFields (string) - 
		
		Returns:
			| ProductVariationDeltaPrice 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/catalog/admin/products/{productCode}/variations/{variationKey}/localizedDeltaPrice?responseFields={responseFields}", "POST", UrlLocation.TenantPod, False);
		url.formatUrl("productCode", productCode);
		url.formatUrl("responseFields", responseFields);
		url.formatUrl("variationKey", variationKey);
		self.client.withResourceUrl(url).withBody(localizedDeltaPrice).execute();
		return self.client.result();

	
		
	def addProductVariationLocalizedPrice(self,localizedPrice, productCode, variationKey, responseFields = None):
		""" 
		
		Args:
			| localizedPrice(localizedPrice) - 
			| productCode (string) - 
			| variationKey (string) - 
			| responseFields (string) - 
		
		Returns:
			| ProductVariationFixedPrice 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/catalog/admin/products/{productCode}/variations/{variationKey}/localizedPrice?responseFields={responseFields}", "POST", UrlLocation.TenantPod, False);
		url.formatUrl("productCode", productCode);
		url.formatUrl("responseFields", responseFields);
		url.formatUrl("variationKey", variationKey);
		self.client.withResourceUrl(url).withBody(localizedPrice).execute();
		return self.client.result();

	
		
	def updateProductVariationLocalizedDeltaPrices(self,localizedDeltaPrice, productCode, variationKey):
		""" 
		
		Args:
			| localizedDeltaPrice(array|localizedDeltaPrice) - 
			| productCode (string) - 
			| variationKey (string) - 
		
		Returns:
			| array of ProductVariationDeltaPrice 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/catalog/admin/products/{productCode}/variations/{variationKey}/localizedDeltaPrice", "PUT", UrlLocation.TenantPod, False);
		url.formatUrl("productCode", productCode);
		url.formatUrl("variationKey", variationKey);
		self.client.withResourceUrl(url).withBody(localizedDeltaPrice).execute();
		return self.client.result();

	
		
	def updateProductVariationLocalizedDeltaPrice(self,localizedDeltaPrice, productCode, variationKey, currencyCode, responseFields = None):
		""" 
		
		Args:
			| localizedDeltaPrice(localizedDeltaPrice) - 
			| productCode (string) - 
			| variationKey (string) - 
			| currencyCode (string) - 
			| responseFields (string) - 
		
		Returns:
			| ProductVariationDeltaPrice 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/catalog/admin/products/{productCode}/variations/{variationKey}/localizedDeltaPrice/{currencyCode}?responseFields={responseFields}", "PUT", UrlLocation.TenantPod, False);
		url.formatUrl("currencyCode", currencyCode);
		url.formatUrl("productCode", productCode);
		url.formatUrl("responseFields", responseFields);
		url.formatUrl("variationKey", variationKey);
		self.client.withResourceUrl(url).withBody(localizedDeltaPrice).execute();
		return self.client.result();

	
		
	def updateProductVariationLocalizedPrices(self,localizedPrice, productCode, variationKey):
		""" 
		
		Args:
			| localizedPrice(array|localizedPrice) - 
			| productCode (string) - 
			| variationKey (string) - 
		
		Returns:
			| array of ProductVariationFixedPrice 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/catalog/admin/products/{productCode}/variations/{variationKey}/localizedPrice", "PUT", UrlLocation.TenantPod, False);
		url.formatUrl("productCode", productCode);
		url.formatUrl("variationKey", variationKey);
		self.client.withResourceUrl(url).withBody(localizedPrice).execute();
		return self.client.result();

	
		
	def updateProductVariationLocalizedPrice(self,localizedPrice, productCode, variationKey, currencyCode, responseFields = None):
		""" 
		
		Args:
			| localizedPrice(localizedPrice) - 
			| productCode (string) - 
			| variationKey (string) - 
			| currencyCode (string) - 
			| responseFields (string) - 
		
		Returns:
			| ProductVariationFixedPrice 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/catalog/admin/products/{productCode}/variations/{variationKey}/localizedPrice/{currencyCode}?responseFields={responseFields}", "PUT", UrlLocation.TenantPod, False);
		url.formatUrl("currencyCode", currencyCode);
		url.formatUrl("productCode", productCode);
		url.formatUrl("responseFields", responseFields);
		url.formatUrl("variationKey", variationKey);
		self.client.withResourceUrl(url).withBody(localizedPrice).execute();
		return self.client.result();

	
		
	def updateProductVariation(self,productVariation, productCode, variationKey, responseFields = None):
		""" 
		
		Args:
			| productVariation(productVariation) - Wrapper for the properties of the specified product variation.
			| productCode (string) - 
			| variationKey (string) - System-generated key that represents the attribute values that uniquely identify a specific product variation.
			| responseFields (string) - 
		
		Returns:
			| ProductVariation 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/catalog/admin/products/{productCode}/variations/{variationKey}?responseFields={responseFields}", "PUT", UrlLocation.TenantPod, False);
		url.formatUrl("productCode", productCode);
		url.formatUrl("responseFields", responseFields);
		url.formatUrl("variationKey", variationKey);
		self.client.withResourceUrl(url).withBody(productVariation).execute();
		return self.client.result();

	
		
	def updateProductVariations(self,productVariations, productCode, responseFields = None):
		""" 
		
		Args:
			| productVariations(productVariations) - Wrapper for the collection of variations configured for the specified product code.
			| productCode (string) - 
			| responseFields (string) - 
		
		Returns:
			| ProductVariationCollection 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/catalog/admin/products/{productCode}/variations?responseFields={responseFields}", "PUT", UrlLocation.TenantPod, False);
		url.formatUrl("productCode", productCode);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).withBody(productVariations).execute();
		return self.client.result();

	
		
	def deleteProductVariation(self,productCode, variationKey):
		""" 
		
		Args:
			| productCode (string) - 
			| variationKey (string) - System-generated key that represents the attribute values that uniquely identify a specific product variation.
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/catalog/admin/products/{productCode}/variations/{variationKey}", "DELETE", UrlLocation.TenantPod, False);
		url.formatUrl("productCode", productCode);
		url.formatUrl("variationKey", variationKey);
		self.client.withResourceUrl(url).execute();

	
		
	def deleteProductVariationLocalizedDeltaPrice(self,productCode, variationKey, currencyCode):
		""" 
		
		Args:
			| productCode (string) - 
			| variationKey (string) - 
			| currencyCode (string) - 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/catalog/admin/products/{productCode}/variations/{variationKey}/localizedDeltaPrice/{currencyCode}", "DELETE", UrlLocation.TenantPod, False);
		url.formatUrl("currencyCode", currencyCode);
		url.formatUrl("productCode", productCode);
		url.formatUrl("variationKey", variationKey);
		self.client.withResourceUrl(url).execute();

	
		
	def deleteProductVariationLocalizedPrice(self,productCode, variationKey, currencyCode):
		""" 
		
		Args:
			| productCode (string) - 
			| variationKey (string) - 
			| currencyCode (string) - 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/catalog/admin/products/{productCode}/variations/{variationKey}/localizedPrice/{currencyCode}", "DELETE", UrlLocation.TenantPod, False);
		url.formatUrl("currencyCode", currencyCode);
		url.formatUrl("productCode", productCode);
		url.formatUrl("variationKey", variationKey);
		self.client.withResourceUrl(url).execute();

	
	
	