
"""
    This code was generated by Codezu.     

    Changes to this file may cause incorrect behavior and will be lost if
    the code is regenerated.
"""


from mozurestsdk.mozuclient import default as default_client
from mozurestsdk.mozuurl import MozuUrl;
from mozurestsdk.urllocation import UrlLocation
from mozurestsdk.apicontext import ApiContext;

class EntityList(object):
	def __init__(self, apiContext: ApiContext = None, mozuClient = None):
		self.client = mozuClient or default_client();
		if (apiContext is not None):
			self.client.withApiContext(apiContext);
		else:
			self.client.withApiContext(ApiContext());
	
	def getEntityLists(self,pageSize = None, startIndex = None, filter = None, sortBy = None, responseFields = None):
		""" 
		
		Args:
			| pageSize (int) - 
			| startIndex (int) - 
			| filter (string) - 
			| sortBy (string) - 
			| responseFields (string) - 
		
		Returns:
			| EntityListCollection 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/platform/entitylists/?pageSize={pageSize}&startIndex={startIndex}&filter={filter}&sortBy={sortBy}&responseFields={responseFields}", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("filter", filter);
		url.formatUrl("pageSize", pageSize);
		url.formatUrl("responseFields", responseFields);
		url.formatUrl("sortBy", sortBy);
		url.formatUrl("startIndex", startIndex);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getEntityList(self,entityListFullName, responseFields = None):
		""" 
		
		Args:
			| entityListFullName (string) - 
			| responseFields (string) - 
		
		Returns:
			| EntityList 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/platform/entitylists/{entityListFullName}?responseFields={responseFields}", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("entityListFullName", entityListFullName);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def createEntityList(self,entityList, responseFields = None):
		""" 
		
		Args:
			| entityList(entityList) - 
			| responseFields (string) - 
		
		Returns:
			| EntityList 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/platform/entitylists/?responseFields={responseFields}", "POST", UrlLocation.TenantPod, False);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).withBody(entityList).execute();
		return self.client.result();

	
		
	def updateEntityList(self,entityList, entityListFullName, responseFields = None):
		""" 
		
		Args:
			| entityList(entityList) - 
			| entityListFullName (string) - 
			| responseFields (string) - 
		
		Returns:
			| EntityList 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/platform/entitylists/{entityListFullName}?responseFields={responseFields}", "PUT", UrlLocation.TenantPod, False);
		url.formatUrl("entityListFullName", entityListFullName);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).withBody(entityList).execute();
		return self.client.result();

	
		
	def deleteEntityList(self,entityListFullName):
		""" 
		
		Args:
			| entityListFullName (string) - 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/platform/entitylists/{entityListFullName}", "DELETE", UrlLocation.TenantPod, False);
		url.formatUrl("entityListFullName", entityListFullName);
		self.client.withResourceUrl(url).execute();

	
	
	