
"""
    This code was generated by Codezu.     

    Changes to this file may cause incorrect behavior and will be lost if
    the code is regenerated.
"""


from mozurestsdk.mozuclient import default as default_client
from mozurestsdk.mozuurl import MozuUrl;
from mozurestsdk.urllocation import UrlLocation

class ReferenceData(object):
	def __init__(self, mozuClient = None):
		self.client = mozuClient or default_client();
	
	def getAddressSchema(self,countryCode = None, responseFields = None):
		""" 
		
		Args:
			| countryCode (string) - The 2-letter country code used to retrieve a specified address schema.
			| responseFields (string) - 
		
		Returns:
			| AddressSchema 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/platform/reference/addressschema/{countryCode}?responseFields={responseFields}", "GET", UrlLocation.HomePod, False);
		url.formatUrl("countryCode", countryCode);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getAddressSchemas(self,responseFields = None):
		""" 
		
		Args:
			| responseFields (string) - 
		
		Returns:
			| AddressSchemaCollection 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/platform/reference/addressschemas?responseFields={responseFields}", "GET", UrlLocation.HomePod, False);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getBehavior(self,behaviorId, responseFields = None):
		""" 
		
		Args:
			| behaviorId (int) - Unique identifier of the behavior.
			| responseFields (string) - 
		
		Returns:
			| Behavior 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/platform/reference/behaviors/{behaviorId}?responseFields={responseFields}", "GET", UrlLocation.HomePod, False);
		url.formatUrl("behaviorId", behaviorId);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getBehaviorCategory(self,categoryId, responseFields = None):
		""" 
		
		Args:
			| categoryId (int) - Unique identifier of the behavior category.
			| responseFields (string) - 
		
		Returns:
			| BehaviorCategory 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/platform/reference/behaviors/categories/{categoryId}?responseFields={responseFields}", "GET", UrlLocation.HomePod, False);
		url.formatUrl("categoryId", categoryId);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getBehaviorCategories(self,responseFields = None):
		""" 
		
		Args:
			| responseFields (string) - 
		
		Returns:
			| BehaviorCategoryCollection 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/platform/reference/behaviors/categories?responseFields={responseFields}", "GET", UrlLocation.HomePod, False);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getBehaviors(self,userType = None, responseFields = None):
		""" 
		
		Args:
			| userType (string) - The user type associated with the behaviors to retrieve.
			| responseFields (string) - 
		
		Returns:
			| BehaviorCollection 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/platform/reference/behaviors?userType={userType}&responseFields={responseFields}", "GET", UrlLocation.HomePod, False);
		url.formatUrl("responseFields", responseFields);
		url.formatUrl("userType", userType);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getContentLocales(self,responseFields = None):
		""" 
		
		Args:
			| responseFields (string) - 
		
		Returns:
			| ContentLocaleCollection 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/platform/reference/contentLocales?responseFields={responseFields}", "GET", UrlLocation.HomePod, False);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getCountries(self,responseFields = None):
		""" 
		
		Args:
			| responseFields (string) - 
		
		Returns:
			| CountryCollection 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/platform/reference/countries?responseFields={responseFields}", "GET", UrlLocation.HomePod, False);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getCountriesWithStates(self,responseFields = None):
		""" 
		
		Args:
			| responseFields (string) - 
		
		Returns:
			| CountryWithStatesCollection 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/platform/reference/countrieswithstates?responseFields={responseFields}", "GET", UrlLocation.HomePod, False);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getCurrencies(self,responseFields = None):
		""" 
		
		Args:
			| responseFields (string) - 
		
		Returns:
			| CurrencyCollection 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/platform/reference/currencies?responseFields={responseFields}", "GET", UrlLocation.HomePod, False);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getTimeZones(self,responseFields = None):
		""" 
		
		Args:
			| responseFields (string) - 
		
		Returns:
			| TimeZoneCollection 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/platform/reference/timezones?responseFields={responseFields}", "GET", UrlLocation.HomePod, False);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getTopLevelDomains(self,responseFields = None):
		""" 
		
		Args:
			| responseFields (string) - 
		
		Returns:
			| TopLevelDomainCollection 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/platform/reference/topleveldomains?responseFields={responseFields}", "GET", UrlLocation.HomePod, False);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getUnitsOfMeasure(self,filter = None, responseFields = None):
		""" 
		
		Args:
			| filter (string) - 
			| responseFields (string) - 
		
		Returns:
			| UnitOfMeasureCollection 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/platform/reference/unitsofmeasure?filter={filter}&responseFields={responseFields}", "GET", UrlLocation.HomePod, False);
		url.formatUrl("filter", filter);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
	
	