
"""
    This code was generated by Codezu.     

    Changes to this file may cause incorrect behavior and will be lost if
    the code is regenerated.
"""


from mozurestsdk.mozuclient import default as default_client
from mozurestsdk.mozuurl import MozuUrl;
from mozurestsdk.urllocation import UrlLocation

class ReferenceData(object):
	def __init__(self, mozuClient = None):
		self.client = mozuClient or default_client();
	
	def getAddressSchema(self,countryCode = None, responseFields = None):
		"""
			Retrieves a specific address schema based on the country code provided. This operation allows the creation of custom shipping and billing address fields.
			Request Params
				string countryCode The 2-letter geographic code representing the country for the physical or mailing address. Currently limited to the US.
				string responseFields Use this field to include those fields which are not included by default.
			Response
				AddressSchema 
		"""

		url = MozuUrl("/api/platform/reference/addressschema/{countryCode}?responseFields={responseFields}", "GET", UrlLocation.HomePod, False);
		url.formatUrl("countryCode", countryCode);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getAddressSchemas(self,responseFields = None):
		"""
			Retrieves the entire list of address schemas that the system supports.
			Request Params
				string responseFields Use this field to include those fields which are not included by default.
			Response
				AddressSchemaCollection 
		"""

		url = MozuUrl("/api/platform/reference/addressschemas?responseFields={responseFields}", "GET", UrlLocation.HomePod, False);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getBehavior(self,behaviorId, responseFields = None):
		"""
			Retrieves the details of a behavior based on the behavior ID specified in the request.
			Request Params
				int behaviorId Unique identifier of the behavior.
				string responseFields Use this field to include those fields which are not included by default.
			Response
				Behavior 
		"""

		url = MozuUrl("/api/platform/reference/behaviors/{behaviorId}?responseFields={responseFields}", "GET", UrlLocation.HomePod, False);
		url.formatUrl("behaviorId", behaviorId);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getBehaviorCategory(self,categoryId, responseFields = None):
		"""
			Retrieves the details of the behavior category specified in the request.
			Request Params
				int categoryId Unique identifier of the category to modify.
				string responseFields Use this field to include those fields which are not included by default.
			Response
				BehaviorCategory 
		"""

		url = MozuUrl("/api/platform/reference/behaviors/categories/{categoryId}?responseFields={responseFields}", "GET", UrlLocation.HomePod, False);
		url.formatUrl("categoryId", categoryId);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getBehaviorCategories(self,responseFields = None):
		"""
			Retrieves the list of behavior categories.
			Request Params
				string responseFields Use this field to include those fields which are not included by default.
			Response
				BehaviorCategoryCollection 
		"""

		url = MozuUrl("/api/platform/reference/behaviors/categories?responseFields={responseFields}", "GET", UrlLocation.HomePod, False);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getBehaviors(self,userType = None, responseFields = None):
		"""
			Retrieves a list of application behaviors.
			Request Params
				string responseFields Use this field to include those fields which are not included by default.
				string userType The user type associated with the behaviors to retrieve.
			Response
				BehaviorCollection 
		"""

		url = MozuUrl("/api/platform/reference/behaviors?userType={userType}&responseFields={responseFields}", "GET", UrlLocation.HomePod, False);
		url.formatUrl("responseFields", responseFields);
		url.formatUrl("userType", userType);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getContentLocales(self,responseFields = None):
		"""
			Retrieves the list of content locales the system supports. Content locales indicate the language used and the country where the language is used.
			Request Params
				string responseFields Use this field to include those fields which are not included by default.
			Response
				ContentLocaleCollection 
		"""

		url = MozuUrl("/api/platform/reference/contentLocales?responseFields={responseFields}", "GET", UrlLocation.HomePod, False);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getCountries(self,responseFields = None):
		"""
			Retrieves the entire list of countries that the system supports.
			Request Params
				string responseFields Use this field to include those fields which are not included by default.
			Response
				CountryCollection 
		"""

		url = MozuUrl("/api/platform/reference/countries?responseFields={responseFields}", "GET", UrlLocation.HomePod, False);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getCountriesWithStates(self,responseFields = None):
		"""
			Retrieves the entire list of countries that the system supports.
			Request Params
				string responseFields A list or array of fields returned for a call. These fields may be customized and may be used for various types of data calls in Mozu. For example, responseFields are returned for retrieving or updating attributes, carts, and messages in Mozu.
			Response
				CountryWithStatesCollection 
		"""

		url = MozuUrl("/api/platform/reference/countrieswithstates?responseFields={responseFields}", "GET", UrlLocation.HomePod, False);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getCurrencies(self,responseFields = None):
		"""
			Retrieves the entire list of currencies that the system supports.
			Request Params
				string responseFields Use this field to include those fields which are not included by default.
			Response
				CurrencyCollection 
		"""

		url = MozuUrl("/api/platform/reference/currencies?responseFields={responseFields}", "GET", UrlLocation.HomePod, False);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getTimeZones(self,responseFields = None):
		"""
			Retrieves the entire list of time zones that the system supports.
			Request Params
				string responseFields Use this field to include those fields which are not included by default.
			Response
				TimeZoneCollection 
		"""

		url = MozuUrl("/api/platform/reference/timezones?responseFields={responseFields}", "GET", UrlLocation.HomePod, False);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getTopLevelDomains(self,responseFields = None):
		"""
			Retrieves the entire list of top-level internet domains that the system supports.
			Request Params
				string responseFields Use this field to include those fields which are not included by default.
			Response
				TopLevelDomainCollection 
		"""

		url = MozuUrl("/api/platform/reference/topleveldomains?responseFields={responseFields}", "GET", UrlLocation.HomePod, False);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getUnitsOfMeasure(self,filter = None, responseFields = None):
		"""
			Retrieves an array list of all units of measure the system supports.
			Request Params
				string filter A set of expressions that consist of a field, operator, and value and represent search parameter syntax when filtering results of a query. Valid operators include equals (eq), does not equal (ne), greater than (gt), less than (lt), greater than or equal to (ge), less than or equal to (le), starts with (sw), or contains (cont). For example - "filter=IsDisplayed+eq+true"
				string responseFields Use this field to include those fields which are not included by default.
			Response
				UnitOfMeasureCollection 
		"""

		url = MozuUrl("/api/platform/reference/unitsofmeasure?filter={filter}&responseFields={responseFields}", "GET", UrlLocation.HomePod, False);
		url.formatUrl("filter", filter);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
	
	