
"""
    This code was generated by Codezu.     

    Changes to this file may cause incorrect behavior and will be lost if
    the code is regenerated.
"""


from mozurestsdk.mozuclient import default as default_client
from mozurestsdk.mozuurl import MozuUrl;
from mozurestsdk.urllocation import UrlLocation
from mozurestsdk.apicontext import ApiContext;

class SecureAppData(object):
	def __init__(self, apiContext: ApiContext = None, mozuClient = None):
		self.client = mozuClient or default_client();
		if (apiContext is not None):
			self.client.withApiContext(apiContext);
		else:
			self.client.withApiContext(ApiContext());
	
	def getDBValue(self,appKeyId, dbEntryQuery, responseFields = None):
		""" 
		
		Args:
			| appKeyId (string) - 
			| dbEntryQuery (string) - 
			| responseFields (string) - 
		
		Returns:
			| JObject 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/platform/secureappdata/{appKeyId}/{*dbEntryQuery}?responseFields={responseFields}", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("appKeyId", appKeyId);
		url.formatUrl("dbEntryQuery", dbEntryQuery);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def createDBValue(self,value, appKeyId, dbEntryQuery):
		""" 
		
		Args:
			| value(value) - 
			| appKeyId (string) - 
			| dbEntryQuery (string) - 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/platform/secureappdata/{appKeyId}/{*dbEntryQuery}", "POST", UrlLocation.TenantPod, False);
		url.formatUrl("appKeyId", appKeyId);
		url.formatUrl("dbEntryQuery", dbEntryQuery);
		self.client.withResourceUrl(url).withBody(value).execute();

	
		
	def updateDBValue(self,value, appKeyId, dbEntryQuery):
		""" 
		
		Args:
			| value(value) - 
			| appKeyId (string) - 
			| dbEntryQuery (string) - 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/platform/secureappdata/{appKeyId}/{*dbEntryQuery}", "PUT", UrlLocation.TenantPod, False);
		url.formatUrl("appKeyId", appKeyId);
		url.formatUrl("dbEntryQuery", dbEntryQuery);
		self.client.withResourceUrl(url).withBody(value).execute();

	
		
	def deleteDBValue(self,appKeyId, dbEntryQuery):
		""" 
		
		Args:
			| appKeyId (string) - 
			| dbEntryQuery (string) - 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/platform/secureappdata/{appKeyId}/{*dbEntryQuery}", "DELETE", UrlLocation.TenantPod, False);
		url.formatUrl("appKeyId", appKeyId);
		url.formatUrl("dbEntryQuery", dbEntryQuery);
		self.client.withResourceUrl(url).execute();

	
	
	