
"""
    This code was generated by Codezu.     

    Changes to this file may cause incorrect behavior and will be lost if
    the code is regenerated.
"""


from mozurestsdk.mozuclient import default as default_client
from mozurestsdk.mozuurl import MozuUrl;
from mozurestsdk.urllocation import UrlLocation
from mozurestsdk.apicontext import ApiContext;

class SiteData(object):
	def __init__(self, apiContext: ApiContext = None, mozuClient = None):
		self.client = mozuClient or default_client();
		if (apiContext is not None):
			self.client.withApiContext(apiContext);
		else:
			self.client.withApiContext(ApiContext());
	
	def getDBValue(self,dbEntryQuery, responseFields = None):
		""" 
		
		Args:
			| dbEntryQuery (string) - The database entry query string used to retrieve the record information.
			| responseFields (string) - 
		
		Returns:
			| string 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/platform/sitedata/{*dbEntryQuery}?responseFields={responseFields}", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("dbEntryQuery", dbEntryQuery);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def createDBValue(self,value, dbEntryQuery):
		""" 
		
		Args:
			| value(value) - The value string to create.
			| dbEntryQuery (string) - The database entry string to create.
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/platform/sitedata/{*dbEntryQuery}", "POST", UrlLocation.TenantPod, False);
		url.formatUrl("dbEntryQuery", dbEntryQuery);
		self.client.withResourceUrl(url).withBody(value).execute();

	
		
	def updateDBValue(self,value, dbEntryQuery):
		""" 
		
		Args:
			| value(value) - The database value to update.
			| dbEntryQuery (string) - The database entry query string used to update the record information.
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/platform/sitedata/{*dbEntryQuery}", "PUT", UrlLocation.TenantPod, False);
		url.formatUrl("dbEntryQuery", dbEntryQuery);
		self.client.withResourceUrl(url).withBody(value).execute();

	
		
	def deleteDBValue(self,dbEntryQuery):
		""" 
		
		Args:
			| dbEntryQuery (string) - The database entry string to delete.
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/platform/sitedata/{*dbEntryQuery}", "DELETE", UrlLocation.TenantPod, False);
		url.formatUrl("dbEntryQuery", dbEntryQuery);
		self.client.withResourceUrl(url).execute();

	
	
	