
"""
    This code was generated by Codezu.     

    Changes to this file may cause incorrect behavior and will be lost if
    the code is regenerated.
"""


from mozurestsdk.mozuclient import default as default_client
from mozurestsdk.mozuurl import MozuUrl;
from mozurestsdk.urllocation import UrlLocation

class Tenant(object):
	def __init__(self, mozuClient = None):
		self.client = mozuClient or default_client();
	
	def getTenant(self,tenantId, responseFields = None):
		""" 
		
		Args:
			| tenantId (int) - 
			| responseFields (string) - 
		
		Returns:
			| Tenant 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/platform/tenants/{tenantId}?responseFields={responseFields}", "GET", UrlLocation.HomePod, False);
		url.formatUrl("responseFields", responseFields);
		url.formatUrl("tenantId", tenantId);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
	
	