
"""
    This code was generated by Codezu.     

    Changes to this file may cause incorrect behavior and will be lost if
    the code is regenerated.
"""


from mozurestsdk.mozuclient import default as default_client
from mozurestsdk.mozuurl import MozuUrl;
from mozurestsdk.urllocation import UrlLocation
from mozurestsdk.apicontext import ApiContext;

class ListView(object):
	def __init__(self, apiContext: ApiContext = None, mozuClient = None):
		self.client = mozuClient or default_client();
		if (apiContext is not None):
			self.client.withApiContext(apiContext);
		else:
			self.client.withApiContext(ApiContext());
	
	def getViewEntity(self,entityListFullName, viewName, entityId, responseFields = None):
		""" 
		
		Args:
			| entityListFullName (string) - 
			| viewName (string) - 
			| entityId (string) - 
			| responseFields (string) - 
		
		Returns:
			| JObject 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/platform/entitylists/{entityListFullName}/views/{viewName}/entities/{entityId}?responseFields={responseFields}", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("entityId", entityId);
		url.formatUrl("entityListFullName", entityListFullName);
		url.formatUrl("responseFields", responseFields);
		url.formatUrl("viewName", viewName);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getViewEntities(self,entityListFullName, viewName, pageSize = None, startIndex = None, filter = None, responseFields = None):
		""" 
		
		Args:
			| entityListFullName (string) - 
			| viewName (string) - 
			| pageSize (int) - 
			| startIndex (int) - 
			| filter (string) - 
			| responseFields (string) - 
		
		Returns:
			| EntityCollection 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/platform/entitylists/{entityListFullName}/views/{viewName}/entities?pageSize={pageSize}&startIndex={startIndex}&filter={filter}&responseFields={responseFields}", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("entityListFullName", entityListFullName);
		url.formatUrl("filter", filter);
		url.formatUrl("pageSize", pageSize);
		url.formatUrl("responseFields", responseFields);
		url.formatUrl("startIndex", startIndex);
		url.formatUrl("viewName", viewName);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getViewEntityContainer(self,entityListFullName, viewName, entityId, responseFields = None):
		""" 
		
		Args:
			| entityListFullName (string) - 
			| viewName (string) - 
			| entityId (string) - 
			| responseFields (string) - 
		
		Returns:
			| EntityContainer 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/platform/entitylists/{entityListFullName}/views/{viewName}/entityContainers/{entityId}?responseFields={responseFields}", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("entityId", entityId);
		url.formatUrl("entityListFullName", entityListFullName);
		url.formatUrl("responseFields", responseFields);
		url.formatUrl("viewName", viewName);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getViewEntityContainers(self,entityListFullName, viewName, pageSize = None, startIndex = None, filter = None, responseFields = None):
		""" 
		
		Args:
			| entityListFullName (string) - 
			| viewName (string) - 
			| pageSize (int) - 
			| startIndex (int) - 
			| filter (string) - 
			| responseFields (string) - 
		
		Returns:
			| EntityContainerCollection 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/platform/entitylists/{entityListFullName}/views/{viewName}/entityContainers?pageSize={pageSize}&startIndex={startIndex}&filter={filter}&responseFields={responseFields}", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("entityListFullName", entityListFullName);
		url.formatUrl("filter", filter);
		url.formatUrl("pageSize", pageSize);
		url.formatUrl("responseFields", responseFields);
		url.formatUrl("startIndex", startIndex);
		url.formatUrl("viewName", viewName);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getEntityListView(self,entityListFullName, viewName, responseFields = None):
		""" 
		
		Args:
			| entityListFullName (string) - 
			| viewName (string) - 
			| responseFields (string) - 
		
		Returns:
			| ListView 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/platform/entitylists/{entityListFullName}/views/{viewName}?responseFields={responseFields}", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("entityListFullName", entityListFullName);
		url.formatUrl("responseFields", responseFields);
		url.formatUrl("viewName", viewName);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getEntityListViews(self,entityListFullName, responseFields = None):
		""" 
		
		Args:
			| entityListFullName (string) - 
			| responseFields (string) - 
		
		Returns:
			| ListViewCollection 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/platform/entitylists/{entityListFullName}/views?responseFields={responseFields}", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("entityListFullName", entityListFullName);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def createEntityListView(self,listView, entityListFullName, responseFields = None):
		""" 
		
		Args:
			| listView(listView) - 
			| entityListFullName (string) - 
			| responseFields (string) - 
		
		Returns:
			| ListView 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/platform/entitylists/{entityListFullName}/views/?responseFields={responseFields}", "POST", UrlLocation.TenantPod, False);
		url.formatUrl("entityListFullName", entityListFullName);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).withBody(listView).execute();
		return self.client.result();

	
		
	def updateEntityListView(self,listView, entityListFullName, viewName, responseFields = None):
		""" 
		
		Args:
			| listView(listView) - 
			| entityListFullName (string) - 
			| viewName (string) - 
			| responseFields (string) - 
		
		Returns:
			| ListView 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/platform/entitylists/{entityListFullName}/views/{viewName}?responseFields={responseFields}", "PUT", UrlLocation.TenantPod, False);
		url.formatUrl("entityListFullName", entityListFullName);
		url.formatUrl("responseFields", responseFields);
		url.formatUrl("viewName", viewName);
		self.client.withResourceUrl(url).withBody(listView).execute();
		return self.client.result();

	
		
	def deleteEntityListView(self,entityListFullName, viewName):
		""" 
		
		Args:
			| entityListFullName (string) - 
			| viewName (string) - 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/platform/entitylists/{entityListFullName}/views/{viewName}", "DELETE", UrlLocation.TenantPod, False);
		url.formatUrl("entityListFullName", entityListFullName);
		url.formatUrl("viewName", viewName);
		self.client.withResourceUrl(url).execute();

	
	
	