
"""
    This code was generated by Codezu.     

    Changes to this file may cause incorrect behavior and will be lost if
    the code is regenerated.
"""


from mozurestsdk.mozuclient import default as default_client
from mozurestsdk.mozuurl import MozuUrl;
from mozurestsdk.urllocation import UrlLocation
from mozurestsdk.apicontext import ApiContext;

class AppPackage(object):
	def __init__(self, apiContext: ApiContext = None, mozuClient = None):
		self.client = mozuClient or default_client();
		if (apiContext is not None):
			self.client.withApiContext(apiContext);
		else:
			self.client.withApiContext(ApiContext());
	
	def getAllPackages(self,startIndex = None, pageSize = None, sortBy = None, filter = None, responseFields = None):
		""" 
		
		Args:
			| startIndex (int) - 
			| pageSize (int) - 
			| sortBy (string) - 
			| filter (string) - 
			| responseFields (string) - 
		
		Returns:
			| PackageSummaryCollection 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/platform/appdev/apppackages/?startIndex={startIndex}&pageSize={pageSize}&sortBy={sortBy}&filter={filter}&responseFields={responseFields}", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("filter", filter);
		url.formatUrl("pageSize", pageSize);
		url.formatUrl("responseFields", responseFields);
		url.formatUrl("sortBy", sortBy);
		url.formatUrl("startIndex", startIndex);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getPackage(self,applicationKey, includeChildren = False, skipDevAccountCheck = False, responseFields = None):
		""" 
		
		Args:
			| applicationKey (string) - 
			| includeChildren (bool) - 
			| skipDevAccountCheck (bool) - 
			| responseFields (string) - 
		
		Returns:
			| Package 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/platform/appdev/apppackages/{applicationKey}/?includeChildren={includeChildren}&skipDevAccountCheck={skipDevAccountCheck}&responseFields={responseFields}", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("applicationKey", applicationKey);
		url.formatUrl("includeChildren", includeChildren);
		url.formatUrl("responseFields", responseFields);
		url.formatUrl("skipDevAccountCheck", skipDevAccountCheck);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getPackages(self,applicationKey, startIndex = None, pageSize = None, sortBy = None, filter = None, responseFields = None):
		""" 
		
		Args:
			| applicationKey (string) - 
			| startIndex (int) - 
			| pageSize (int) - 
			| sortBy (string) - 
			| filter (string) - 
			| responseFields (string) - 
		
		Returns:
			| PackageCollection 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/platform/appdev/apppackages/applications/{applicationKey}/packages/?startIndex={startIndex}&pageSize={pageSize}&sortBy={sortBy}&filter={filter}&responseFields={responseFields}", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("applicationKey", applicationKey);
		url.formatUrl("filter", filter);
		url.formatUrl("pageSize", pageSize);
		url.formatUrl("responseFields", responseFields);
		url.formatUrl("sortBy", sortBy);
		url.formatUrl("startIndex", startIndex);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getApplicationSummaryChildren(self,appId):
		""" 
		
		Args:
			| appId (string) - 
		
		Returns:
			| array of ApplicationSummary 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/platform/appdev/apppackages/apps/{appId}/", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("appId", appId);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getApplicationSummaryParents(self,startIndex = None, pageSize = None, sortBy = None, filter = None, responseFields = None):
		""" 
		
		Args:
			| startIndex (int) - 
			| pageSize (int) - 
			| sortBy (string) - 
			| filter (string) - 
			| responseFields (string) - 
		
		Returns:
			| ApplicationSummaryCollection 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/platform/appdev/apppackages/collection/?startIndex={startIndex}&pageSize={pageSize}&sortBy={sortBy}&filter={filter}&responseFields={responseFields}", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("filter", filter);
		url.formatUrl("pageSize", pageSize);
		url.formatUrl("responseFields", responseFields);
		url.formatUrl("sortBy", sortBy);
		url.formatUrl("startIndex", startIndex);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def clonePackage(self,applicationKey, packageName, responseFields = None):
		""" 
		
		Args:
			| applicationKey (string) - 
			| packageName (string) - 
			| responseFields (string) - 
		
		Returns:
			| Package 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/platform/appdev/apppackages/{applicationKey}/clone/{packageName}?responseFields={responseFields}", "POST", UrlLocation.TenantPod, False);
		url.formatUrl("applicationKey", applicationKey);
		url.formatUrl("packageName", packageName);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def createNewCorePackage(self,packageRequest, responseFields = None):
		""" 
		
		Args:
			| packageRequest(packageRequest) - 
			| responseFields (string) - 
		
		Returns:
			| Package 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/platform/appdev/apppackages/create?responseFields={responseFields}", "POST", UrlLocation.TenantPod, False);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).withBody(packageRequest).execute();
		return self.client.result();

	
		
	def createPackage(self,package, projectId = None, responseFields = None):
		""" 
		
		Args:
			| package(package) - 
			| projectId (int) - 
			| responseFields (string) - 
		
		Returns:
			| Package 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/platform/appdev/apppackages/project/?projectId={projectId}&responseFields={responseFields}", "POST", UrlLocation.TenantPod, False);
		url.formatUrl("projectId", projectId);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).withBody(package).execute();
		return self.client.result();

	
		
	def updatePackage(self,package, applicationKey, responseFields = None):
		""" 
		
		Args:
			| package(package) - 
			| applicationKey (string) - 
			| responseFields (string) - 
		
		Returns:
			| Package 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/platform/appdev/apppackages/{applicationKey}/?responseFields={responseFields}", "PUT", UrlLocation.TenantPod, False);
		url.formatUrl("applicationKey", applicationKey);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).withBody(package).execute();
		return self.client.result();

	
		
	def deletePackage(self,applicationKey):
		""" 
		
		Args:
			| applicationKey (string) - 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/platform/appdev/apppackages/{applicationKey}/", "DELETE", UrlLocation.TenantPod, False);
		url.formatUrl("applicationKey", applicationKey);
		self.client.withResourceUrl(url).execute();

	
	
	