
"""
    This code was generated by Codezu.     

    Changes to this file may cause incorrect behavior and will be lost if
    the code is regenerated.
"""


from mozurestsdk.mozuclient import default as default_client
from mozurestsdk.mozuurl import MozuUrl;
from mozurestsdk.urllocation import UrlLocation
from mozurestsdk.apicontext import ApiContext;

class CarrierConfiguration(object):
	def __init__(self, apiContext: ApiContext = None, mozuClient = None):
		self.client = mozuClient or default_client();
		if (apiContext is not None):
			self.client.withApiContext(apiContext);
		else:
			self.client.withApiContext(ApiContext());
	
	def getConfigurations(self,startIndex = None, pageSize = None, sortBy = None, filter = None, responseFields = None):
		""" 
		
		Args:
			| startIndex (int) - 
			| pageSize (int) - 
			| sortBy (string) - 
			| filter (string) - 
			| responseFields (string) - 
		
		Returns:
			| CarrierConfigurationCollection 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/shipping/admin/carriers/?startIndex={startIndex}&pageSize={pageSize}&sortBy={sortBy}&filter={filter}&responseFields={responseFields}", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("filter", filter);
		url.formatUrl("pageSize", pageSize);
		url.formatUrl("responseFields", responseFields);
		url.formatUrl("sortBy", sortBy);
		url.formatUrl("startIndex", startIndex);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def getConfiguration(self,carrierId, responseFields = None):
		""" 
		
		Args:
			| carrierId (string) - 
			| responseFields (string) - 
		
		Returns:
			| CarrierConfiguration 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/shipping/admin/carriers/{carrierId}?responseFields={responseFields}", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("carrierId", carrierId);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def createConfiguration(self,carrierConfiguration, carrierId, responseFields = None):
		""" 
		
		Args:
			| carrierConfiguration(carrierConfiguration) - 
			| carrierId (string) - 
			| responseFields (string) - 
		
		Returns:
			| CarrierConfiguration 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/shipping/admin/carriers/{carrierId}?responseFields={responseFields}", "POST", UrlLocation.TenantPod, False);
		url.formatUrl("carrierId", carrierId);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).withBody(carrierConfiguration).execute();
		return self.client.result();

	
		
	def updateConfiguration(self,carrierConfiguration, carrierId, responseFields = None):
		""" 
		
		Args:
			| carrierConfiguration(carrierConfiguration) - 
			| carrierId (string) - 
			| responseFields (string) - 
		
		Returns:
			| CarrierConfiguration 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/shipping/admin/carriers/{carrierId}?responseFields={responseFields}", "PUT", UrlLocation.TenantPod, False);
		url.formatUrl("carrierId", carrierId);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).withBody(carrierConfiguration).execute();
		return self.client.result();

	
		
	def deleteConfiguration(self,carrierId):
		""" 
		
		Args:
			| carrierId (string) - 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/shipping/admin/carriers/{carrierId}", "DELETE", UrlLocation.TenantPod, False);
		url.formatUrl("carrierId", carrierId);
		self.client.withResourceUrl(url).execute();

	
	
	