
"""
    This code was generated by Codezu.     

    Changes to this file may cause incorrect behavior and will be lost if
    the code is regenerated.
"""


from mozurestsdk.mozuclient import default as default_client
from mozurestsdk.mozuurl import MozuUrl;
from mozurestsdk.urllocation import UrlLocation
from mozurestsdk.apicontext import ApiContext;

class CustomerAuthTicket(object):
	def __init__(self, apiContext: ApiContext = None, mozuClient = None):
		self.client = mozuClient or default_client();
		if (apiContext is not None):
			self.client.withApiContext(apiContext);
		else:
			self.client.withApiContext(ApiContext());
	
	def createAnonymousShopperAuthTicket(self,responseFields = None):
		""" 
		
		Args:
			| responseFields (string) - 
		
		Returns:
			| CustomerAuthTicket 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/customer/authtickets/anonymousshopper?responseFields={responseFields}", "GET", UrlLocation.TenantPod, False);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
		
	def createUserAuthTicket(self,userAuthInfo, responseFields = None):
		""" 
		
		Args:
			| userAuthInfo(userAuthInfo) - The authentication information required to generate an authetication ticket for a user, which consists of a user name and password.
			| responseFields (string) - 
		
		Returns:
			| CustomerAuthTicket 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/customer/authtickets/?responseFields={responseFields}", "POST", UrlLocation.TenantPod, False);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).withBody(userAuthInfo).execute();
		return self.client.result();

	
		
	def refreshUserAuthTicket(self,refreshToken, responseFields = None):
		""" 
		
		Args:
			| refreshToken (string) - The refresh token string required to refresh a user's authentication ticket.
			| responseFields (string) - 
		
		Returns:
			| CustomerAuthTicket 
		
		Raises:
			| ApiException
		
		"""

		url = MozuUrl("/api/commerce/customer/authtickets/refresh?refreshToken={refreshToken}&responseFields={responseFields}", "PUT", UrlLocation.TenantPod, False);
		url.formatUrl("refreshToken", refreshToken);
		url.formatUrl("responseFields", responseFields);
		self.client.withResourceUrl(url).execute();
		return self.client.result();

	
	
	